### ISSUE TITLE
Support for 9-patch images 

### ISSUE THREAD

**Issue by birbilis** [skia4delphi/skia4delphi#102]
I came across this page:
https://docwiki.embarcadero.com/RADStudio/Sydney/en/Using_9-patch_Images_in_Android
which mentions .9.png files from Android

These are useful since they are bitmaps that adapt as they're scaled without distorting their border area

They're made with a draw9patch tool:
https://developer.android.com/studio/write/draw9patch
included in Android Studio:
https://www.youtube.com/watch?v=5P9OQ53ha0U

More info on 9-patch images:
https://wiresareobsolete.com/2010/06/9-patches/
https://developer.android.com/guide/topics/graphics/drawables#nine-patch

Seems Skia supports such images judging from the info at:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/segmented

> The SkiaSharp SKCanvas object defines a method named DrawBitmapNinePatch and two methods named DrawBitmapLattice that are very similar. Both these methods render a bitmap to the size of a destination rectangle, but instead of stretching the bitmap uniformly, they display portions of the bitmap in its pixel dimensions and stretch other parts of the bitmap so that it fits the rectangle

There's also this other Delphi library for 9-patch images: https://github.com/yypbd/yypbd-Delphi-NinePatch

So could Skia4Delphi add support for loading and displaying .9.png files? (or maybe even any lossless bitmap format as .9.xxx [for lossy probably can't do as compression could corrupt the extra info] or who knows, even for svg somehow)

**Comment by viniciusfbb** [comment]
Skia doesn't officially support 9 patch images and we want to avoid customizations at all costs, to make the api as close to the original as possible. However it has something similar:

https://github.com/skia4delphi/skia4delphi/blob/50f5adbabda8281b211c1df0feee9e7d2257542f/Source/Skia.pas#L487

which you inform the central rectangle that will be resized horizontally and vertically, preserving the corners. In fact, in our demo there is an example of this:

![Demo](https://github.com/skia4delphi/skia4delphi/blob/main/Assets/Documents/Demo-Screens/images-drawing-9-patch.png?raw=true)

https://github.com/skia4delphi/skia4delphi/blob/50f5adbabda8281b211c1df0feee9e7d2257542f/Samples/Demo/FMX/Source/Sample.Form.Image.pas#L86-L95

**Comment by birbilis** [comment]
probably the image control (which is extra compared to Skia core) could have some properties to do that 9-patch effect when it is resized (aka preserve its corners [as defined by properties]) and only resize a core rectangular area)

such properties would probably be PatchLeft, PatchRight, PatchTop, PatchBottom (real numbers) maybe defined in a Patch rect structure to be grouped together and handled more easily (copied etc.). The default value would be 0, aka no 9-patching effect upon resizing
