### ISSUE TITLE
Compatibility with C++ Builder

### ISSUE THREAD

**Issue by sfirouz** [skia4delphi/skia4delphi#103]
The library installs from GetIt in "C++ Builder" 11.1, but just putting a TSkSvg on a form and compiling it will produce 431 errors starting with Release() function of ISkReferenceCountedBase returns void but should return ULONG (Skia.Bindings.hpp Line 175).
[Skia1.zip](https://github.com/skia4delphi/skia4delphi/files/8592236/Skia1.zip)

**Comment by viniciusfbb** [comment]
Skia4Delphi is not yet compatible with C++ Builder. We intend to make it compatible, but it's not yet our priority.

**Comment by viniciusfbb** [comment]
We started porting to C++Builder. You can follow through issue #107
