### ISSUE TITLE
TSkAnimatedImage: play on mouseover/click option? (suggestion)

### ISSUE THREAD

**Issue by Brnoch** [skia4delphi/skia4delphi#104]
Hi, 
Could the animation start when the mouse is over the image or when the user clicks on it ? This would allow to implement animated buttonis, as in these examples: https://icons8.com/animated-icons/material-filled, or these: https://useanimations.com/#explore
In the second linked page, the behaviour is more complex: for example, when you click on the "Menu V2" button, the hamburger icons transforms to a X, and when you click once again it reverts to the hamburger.

This is a suggestion, I don't know if it can be done and if it's complicated or not!

**Comment by viniciusfbb** [comment]
You can easily start and stop just changing the Enabled property of the TSkAnimatedImage control. In next version we will add more features to control better the animation. (Like inverse, reverse, delay, …)

**Comment by Brnoch** [comment]
The trouble is that all the Clik/MouseEnter/MouseMove... events don't fire when the component is disabled.
And if the Enabled property could be used for another purpose than the animation, I would use it to indicate if the "button" is available or not.

**Comment by viniciusfbb** [comment]
Fixed in [new release v4.0.0](https://github.com/skia4delphi/skia4delphi/releases)
