### ISSUE TITLE
isn't the font the current font on the system when using Skia?

### ISSUE THREAD

**Issue by DValue** [skia4delphi/skia4delphi#109]
For titles, isn't the font the current font on the system when using Skia?

**Comment by DValue** [comment]
I forgot to mention that I'm on Android, there are no tests on other platforms

**Comment by viniciusfbb** [comment]
Hi @DValue, thank you to report the issue.

Should be. It's different? It would be interesting for you to take a print with and without GlobalUseSkia := True to compare.

**Comment by DValue** [comment]
Hi @viniciusfbb.
Without GlobalUseSkia := True, the UI uses the system's current font.Not with GlobalUseSkia := True

**Comment by viniciusfbb** [comment]
Confirmed issue. The problem occurs when the system font is a custom font, i.e., different than Roboto.

**Comment by viniciusfbb** [comment]
**Updating**

Unfortunately on Android there is no official api to get the system's default font family. Therefore, the IFMXSystemFontService.FamilyName (implemented in the FMX.Platform.Metrics.Android unit), always returns a 'Roboto' const. Internally Skia also does this, if you leave an empty string in fontFamily, it will treat it as 'Roboto'. This is a problem that in [Flutter also happens](https://stackoverflow.com/questions/51913485/how-to-use-the-devices-default-font-in-flutter), that also uses Skia.

I opened a discussion about it in the Skia community, as I see this as an Skia issue: https://groups.google.com/g/skia-discuss/c/6n2SetxLvwA
I will now wait for further information from them.

**Comment by viniciusfbb** [comment]
Unfortunately, there is nothing to be done in this case. On Android there is no API that informs the name of the system's default font and Skia always considers Roboto as the default font on Android, and this is a problem that also happens with flutter and Xamarin applications, or any other application that uses Skia on Android.

So, for now I will close this issue, but I do not rule out reopening it in the future when it is possible to do something.

**Comment by viniciusfbb** [comment]
Registering new information. There is a font setting in Skia Android that might be the solution: https://github.com/google/skia/blob/35aef51800ea1def8288594765d35da4088a17f5/include/ports/SkFontMgr_android.h#L19

**Comment by DValue** [comment]
Thanks, so what should I do with it?

**Comment by viniciusfbb** [comment]
> Thanks, so what should I do with it?

Nothing changes for now. I'm just logging here for future research
