### ISSUE TITLE
TRectangle with Fill.Kind = Bitmap paints black when no Bitmap assigned

### ISSUE THREAD

**Issue by alexdgs** [skia4delphi/skia4delphi#110]
I tested this on an empty FMX project using Delphi 11.1 and Skia4Delphi 3.4.0. The project runs on Windows 11.

With `GlobalUseSkiaRasterWhenAvailable := False` and `GlobalUseSkia := True`:
![image](https://user-images.githubusercontent.com/7460734/169057289-f9cbfc5e-66ac-46fc-88a6-5aad3ae40df1.png)

Without Skia:
![image](https://user-images.githubusercontent.com/7460734/169057489-2920f7c0-fb00-4c7e-80a5-84a7002bc07c.png)

Interesting that TImage is not affected by this issue.

**Comment by viniciusfbb** [comment]
Hi @alexdgs, thank you very much to report the issue.

Can you test with `GlobalUseSkiaRasterWhenAvailable := True` and `GlobalUseSkia := True`?

**Comment by alexdgs** [comment]
Hi @viniciusfbb. Seems like there is no difference.
![image](https://user-images.githubusercontent.com/7460734/169064954-30b77dd7-9b92-463c-89d2-311a560e2537.png)

**Comment by viniciusfbb** [comment]
Fixed in our new release [3.4.1](https://github.com/skia4delphi/skia4delphi/releases)
