### ISSUE TITLE
Cannot change SkiaLabel width at design time. 

### ISSUE THREAD

**Issue by tanghzuk188** [skia4delphi/skia4delphi#114]
As a default feature of Label, I need to visualise the label actual size at design time so I know how big it should be without overlapping other compoents. But in FMX project, this is not possbile. Width cannot be changed.

**Comment by viniciusfbb** [comment]
Hi @tanghzuk188!
To set custom sizes in TSkLabel control, you need to set the property AutoSize to False.

**Comment by tanghzuk188** [comment]
Thanks for the quick response. It works now. The default FMX.autosize is false, so neglect it. my fault. this is a really good package. Do you have any comments on my another question at stack https://stackoverflow.com/questions/72306293/skia4delphi-how-to-make-mixed-coloured-animated-text-word . thanks

**Comment by viniciusfbb** [comment]
Do you have access to Telegram? In our official [Telegram group](https://t.me/skia4delphi), I posted a few days ago a small example of a text animation. How can you make your animation based on my example...

https://user-images.githubusercontent.com/11139086/173080374-d38da8b9-b603-4a89-a133-1a8b97fb9d68.mp4

[TextEffect.zip](https://github.com/skia4delphi/skia4delphi/files/8879430/TextEffect.zip)

**Comment by tanghzuk188** [comment]
thanks for the small sample. I will study it. Not in Telegram group yet, will register one later.
