### ISSUE TITLE
Square at the end of a Text property

### ISSUE THREAD

**Issue by salvadordf** [skia4delphi/skia4delphi#115]
Adding an ampersand character to a Text property to enable a hotkey shows an square character at the end.

Steps to reproduce in Windows : 
1. Create a new empty Firemonkey application.
2. Drop a button on the form.
3. Set the button's Text property to &Text.
4. Run the application and the button will show "Text□"

**Comment by viniciusfbb** [comment]
Fixed in our new release [3.4.1](https://github.com/skia4delphi/skia4delphi/releases)
