### ISSUE TITLE
TSkGraphic CanLoadFromStream does not reset back stream position

### ISSUE THREAD

**Issue by PieterScheldeman** [skia4delphi/skia4delphi#123]
Hi,

This code

```
{$IF CompilerVersion >= 32}
class function TSkGraphic.CanLoadFromStream(AStream: TStream): Boolean;
const
  SupportedFormats = [TSkEncodedImageFormat.WEBP, TSkEncodedImageFormat.WBMP, TSkEncodedImageFormat.DNG];
var
  LCodec: ISkCodec;
begin
  LCodec := TSkCodec.MakeFromStream(AStream);
  Result := Assigned(LCodec) and (LCodec.EncodedImageFormat in SupportedFormats);
end;
{$ENDIF}
```

should change to

```
{$IF CompilerVersion >= 32}
class function TSkGraphic.CanLoadFromStream(AStream: TStream): Boolean;
const
  SupportedFormats = [TSkEncodedImageFormat.WEBP, TSkEncodedImageFormat.WBMP, TSkEncodedImageFormat.DNG];
var
  LCodec: ISkCodec;
  p: Int64;
begin
  p := AStream.Position;
  try
    LCodec := TSkCodec.MakeFromStream(AStream);
    Result := Assigned(LCodec) and (LCodec.EncodedImageFormat in SupportedFormats);
  finally
    AStream.Position := p;
  end;
end;
{$ENDIF}
```

Because it doesn't take other registered picture formats into account from other third party developers. When TSkGraphic class is registered and is checked first, the stream position is corrupt and then doesn't allow other classes to load the stream. Please apply this fix to make TSkGraphic go hand in hand with other custom picture format classes.

**Comment by viniciusfbb** [comment]
Hi @PieterScheldeman, thank you so much for reporting the issue!

We recently discovered this issue and fixed it in our development branch: https://github.com/skia4delphi/skia4delphi/commit/dfc7aeecc3257c0b619f67c67af347e81ade6e0e

The next release with this fix will be available in a few weeks.

Duplication of #111
