### ISSUE TITLE
Basic Questions: Drawing and Moving

### ISSUE THREAD

**Issue by JediThumper** [skia4delphi/skia4delphi#124]
Hi

Sorry in advance for the basic questions, I'm New to Skia and graphics generally.

To learn more I am creating a basic drawing program.

I hold a list of DrawingObjects: each has a BoundsRect and Path and Paint properties. This works great.. I can draw to an SKPaintobox Canvas by iterating through my list and drawing each object in the Draw event. 

So now I would like to move an object with mousemove. 

Some questions, please.

I move the DrawingObject by recalculating the BoundsRect.. Is this correct? Is there a better way?

When I move one object I have to redraw (from mousemove event) the whole SKpaintbox, This causes a lot of flickering! is there a better way?

Does SKia have layers? I have found mention but no examples. 

Reading a bit more , Should I transform the path rather than move the bounds and recalculate the path?

Sorry for the dum questions.

Many thanks 

Alan

**Comment by viniciusfbb** [comment]
Hi @JediThumper, it's okay to post any kind of questions. We are also available in the Telegram group for quick questions: https://t.me/skia4delphi

Your problem will probably be solved by changing the DoubleBuffered property to True in your SkPaintBox's parent control.

**Comment by JediThumper** [comment]
Thank you DoubleBuffered Fixed the problem.

Will move questions to Telegram
