### ISSUE TITLE
When will the next version be available?

### ISSUE THREAD

**Issue by Brnoch** [skia4delphi/skia4delphi#128]
I presume that the next version introduces some major changes and new features.
Do you have any visibity on the time when it will be available?
I don't want to put any pressure, I would just be so pleased to install it!
Thanks for you great work

**Comment by viniciusfbb** [comment]
Hi @Brnoch.

Our next release will be a major, v4.0.0, and we plan to add a lot of new features. However, some of these are complex and we have no way of predicting the exact time. We want everything ready by the end of July. Meanwhile, anyone can use the development version, "dev" branch. To use it, just:

1. Download the "dev" branch zip: https://github.com/skia4delphi/skia4delphi/archive/refs/heads/dev.zip
2. Install [InnoSetup](https://jrsoftware.org/isdl.php)
3. Open and Run our setup script: `skia4delphi\Tools\Setup\Setup.iss`

**Comment by viniciusfbb** [comment]
Another info about "dev" branch: You can follow the progress at https://github.com/orgs/skia4delphi/projects/10/views/1?layout=board

**Comment by Brnoch** [comment]
HI @viniciusfbb 
Thanks a lot for the information. This is precious. I'll follow the progress of the dev branch and wait for the final realease, as I use your components in a "production" software.
