### ISSUE TITLE
Delphi Community Edition not supported for Mac

### ISSUE THREAD

**Issue by peardox** [skia4delphi/skia4delphi#129]
I just tried running a test project on the Mac and during compilation I'm informed that CE won't work on Mac (didn't see this mentioned in the README.md)

**Comment by viniciusfbb** [comment]
Hello @peardox!

Maybe it's not clear, but it's stated in the Readme: https://github.com/skia4delphi/skia4delphi#compatibility

In Delphi 10.4 Sydney CE, only Windows and Android are supported. It would be a lot of work for us to maintain this backwards compatibility in RAD Studio, at least for macOS and iOS, so we have no intention of changing that.
