### ISSUE TITLE
OffScreen Drawing 

### ISSUE THREAD

**Issue by peardox** [skia4delphi/skia4delphi#135]
Not sure if this is related to #120 so here goes...

I've got a stack of identically sized FMX TSkPaintBox-es, each contain images. Then I've got a SKRuntimeEffect Shader that alters the images based on colour and/or transparency to provide paint-program style 'layers'. When this renders to the screen I end up with a layered image being displayed - all this works perfectly.

However, the images may be (much?) larger than the TSkPaintbox so the Shader also scales so the displayed composite looks correct.

What I want to do is to be able to render the composite at full resolution so that e.g. a displayed but scaled 4k image renders to the full 4k off-screen and can then be saved to  disk as output.

There are two methods that occur - the preferable solution is to render the result using Skia, this is desirable as the Shaders already do everything.

If this is not possible (or too much hassle) I can always replicate the Shaders in Pascal and build the resultant image that way.

If this is trivial a small FMX example would be very much appreciated (I'm sure it would also be of interest to other users of this project as the technique is really useful)

**Comment by viniciusfbb** [comment]
Hi @peardox!

Basically what you want would be to save a screenshot of your TSkPaintBox(es) with a custom size? There are several ways to do this, but if the controls are just TSkPaintBox and they all have the same dimension, it could be done very simply:

```delphi
procedure SaveLayersScreenShot(const AWidth, AHeight: Integer);
var
  LSurface: ISkSurface;
begin
  LSurface := TSkSurface.MakeRaster(AWidth, AHeight);
  LSurface.Canvas.Clear(TAlphaColors.Null);

  // SkPaintBox1 - Layer 1
  if Assigned(SkPaintBox1.OnDraw) then
    SkPaintBox1.OnDraw(SkPaintBox1, LSurface.Canvas, RectF(0, 0, AWidth, AHeight), 1);

  // SkPaintBox2 - Layer 2
  if Assigned(SkPaintBox2.OnDraw) then
    SkPaintBox2.OnDraw(SkPaintBox2, LSurface.Canvas, RectF(0, 0, AWidth, AHeight), 1);

  // Layer n...

  LSurface.MakeImageSnapshot.EncodeToFile('big-screen-shot.png');
end;
```

**Comment by peardox** [comment]
Thanks a million @viniciusfbb - your helpful attitude is really appreciated, far less people than you'd imagine have your kind of self-motivated helpfulness.

While this may be simple to some it's not to others so it really does deserve adding to the README.md

I'll go try it out immediately, thanks again.

**Comment by peardox** [comment]
Hmm - it's extremely slow. I'm timing c. 12 seconds for a test 2 layer 2400x3000 image (decent laptop)

Still, it does work as desired.

On screen it's super-fast of course

**Comment by viniciusfbb** [comment]
Oh yes. What is happening is that the canvas of the screen is rendered on the GPU, while the canvas of surfaces created by MakeRaster (our code) are rendered on the CPU. There is generally no performance problem drawing on raster (CPU) surfaces, except for heavier operations like shader. In this case, let's try another code that creates a surface that is rendered internally by the GPU:

```Delphi
uses
  Skia.FMX.Graphics;

procedure TForm1.SaveLayersScreenShot(const AWidth, AHeight: Integer);
var
  LSurface: ISkSurface;
begin
  if (Self.Canvas is TGrCanvasCustom) and Assigned(TGrCanvasCustom(Self.Canvas).Context) then
    LSurface := TSkSurface.MakeRenderTarget(TGrCanvasCustom(Self.Canvas).Context, False, TSkImageInfo.Create(AWidth, AHeight))
  else
    LSurface := TSkSurface.MakeRaster(AWidth, AHeight);
  LSurface.Canvas.Clear(TAlphaColors.Null);

  // SkPaintBox1 - Layer 1
  if Assigned(SkPaintBox1.OnDraw) then
    SkPaintBox1.OnDraw(SkPaintBox1, LSurface.Canvas, RectF(0, 0, AWidth, AHeight), 1);

  // SkPaintBox2 - Layer 2
  if Assigned(SkPaintBox2.OnDraw) then
    SkPaintBox2.OnDraw(SkPaintBox2, LSurface.Canvas, RectF(0, 0, AWidth, AHeight), 1);

  // Layer n...

  LSurface.MakeImageSnapshot.EncodeToFile('big-screen-shot.png');
end;
```

**Comment by peardox** [comment]
You're my hero!

**Comment by peardox** [comment]
Well, that's much better - 1.5 secs but...

I'm not sure if this is a bug or not....

After it saves the image the form no longer updates or responds to clicks.

At first I thought that I has something wrong in the label that displays the timing so I added a ShowMessage with the timing just to check (which is how I know how long it takes)

It appears that OS controls still function but other stuff don't. Resizing the form results in a blank form...

If you need a quick test just grab https://github.com/peardox/Compositing compile + run then select Save Composite from File menu then everything will stop responding. Sorry I ain't got anything simple to hand...

**Comment by viniciusfbb** [comment]
Excellent! About the problem, I have to do some tests, maybe it's the lack of FlushAndSubmit, or the lack of a MakeRasterImage at the end... The truth is that it's quite annoying to mess with GPU surfaces, especially when they are global variables (because they would need to register some messages to detect context destruction), but in your case it's just a local temporary surface, so it won't be complicated.

I'm just going to do some tests tomorrow to adjust this code I gave you.
