### ISSUE TITLE
A rather uninformative error message...

### ISSUE THREAD

**Issue by peardox** [skia4delphi/skia4delphi#138]
This is what happens when you try setting a Uniform when it doesn't exist in the sksl shader...

![image](https://user-images.githubusercontent.com/1549219/178822747-cd40f0cb-8cee-4f33-924f-3a90ced237c6.png)

The error message could be a little more informative...

Of course this can be avoided by checking if it exists first...

**Comment by viniciusfbb** [comment]
Fixed in our new release [3.4.1](https://github.com/skia4delphi/skia4delphi/releases)
