### ISSUE TITLE
Iterate through path

### ISSUE THREAD

**Issue by TomDannert** [skia4delphi/skia4delphi#14]
How can i iterate through path object? In the example below, the verb always returns "out of bounds".

```
var
  LElem : TSkPathIteratorElem;
begin
   for LElem in APath.GetIterator(False) do
   begin
      case LElem.Verb of **<-- out of bounds**
      ...
end;

```
Thanks in advance for the answer

**Comment by viniciusfbb** [comment]
The problem was solved in new release. Please download new version 3.0.0.
