### ISSUE TITLE
Can't convert my FMX example to SKIA "Item not found" - WIN32

### ISSUE THREAD

**Issue by maurobotta** [skia4delphi/skia4delphi#140]
Hi

I can't convert my small project FMX ( without skia),  i have watch Skia4Delphi.dproj project for template.

At startup my app crash.

I have read your doc here https://github.com/skia4delphi/skia4delphi for convert fmx project to force it to render with Skia.

Zero Skia Component. only force a best render with Fmx.

Error:
First chance exception at $770FCA42. Exception class EListError with message 'Item not found'. Process testapp.exe (24220)

I have add to deploy sk4d.dll of course. i have made a fast test with Android 64 and crash it, too.

Delphi 11.1.5, compiler : WIN32
OS:Windows 10.

source error: 

Skia.FMX.Graphics.pas

var
  CanvasService: TSkCanvasService;
initialization

   
  CanvasService := TSkCanvasService.Create(IFMXCanvasService(TPlatformServices.Current.GetPlatformService(IFMXCanvasService)));  
  HERE ERROR

  TPlatformServices.Current.RemovePlatformService(IFMXCanvasService);
  TPlatformServices.Current.AddPlatformService(IFMXCanvasService, CanvasService);
{$ENDREGION}
end.

My test projet dpr:

program simpleFmxClear;
uses
  System.StartUpCopy,
  FMX.Forms,
  FMX.Types,
  Skia.FMX,

begin
GlobalUseMetal := True;
end;

**Comment by viniciusfbb** [comment]
Hi @maurobotta!

This error is unexpected. Did you follow the steps correctly?

1) Enable your project to use the Skia lib:
https://user-images.githubusercontent.com/16469061/153612789-38488c75-930a-48ac-8a6b-ea303f403e9e.png#gh-dark-mode-only

After that, it is necessary to clear the project. This step of enabling the project is used to configure the binaries of the library, that is, after Windows compilations for example, you will see that sk4d.dll will automatically appear in the same folder as your exe.

2) To enable the "App render with Skia" feature, you must change your dpr, but please follow the same order as the units:

```delphi
uses
  System.StartUpCopy,
  FMX.Forms,
  Skia.FMX,
  Unit1 in 'Unit1.pas' {Form1};

{$R *.res}

begin
  GlobalUseSkia := True;
  Application.Initialize;
  ...
```

3) If the error persists, try on a blank project.

**Comment by viniciusfbb** [comment]
Another question, does the demo work correctly?

**Comment by viniciusfbb** [comment]
@maurobotta  Any news?

**Comment by viniciusfbb** [comment]
Issue closed due to lack of feedback. Feel free to open a new issue or even keep chatting here as soon as you have any news.
