### ISSUE TITLE
SVGs containing Unicode characters gets scrambled with TSkSVG

### ISSUE THREAD

**Issue by omonien** [skia4delphi/skia4delphi#142]
If you have some simple SVG graphics that contains some Unicode text, then TSkSVG renders all special characters to garbage.

The upper line in the screenshot is all vectors; that's how the text in the lower line should look like.

<img width="511" alt="Bildschirmfoto 2022-07-24 um 15 17 59" src="https://user-images.githubusercontent.com/1296517/180649660-c89684a4-7843-4aa6-b04e-d08a562a829c.png">

The actual SVG file renders correctly in Chrome. See attached "umlauts.svg" file.
![Umlauts](https://user-images.githubusercontent.com/1296517/180649705-c5ef83f0-067d-4d83-a92a-3f157c8bd5bf.svg)

**Comment by omonien** [comment]
Some more investigation revealed that this is actually a Delphi/RTL bug:
The SVG example file is UTF-8 encoded but has no BOM (which is perfectly valid). Unfortunately, though, Delphi, up to the newest 11.x versions can not detect UTF-8 WITHOUT BOM. 
Once you re-encode the file including BOM it works fine.

**Comment by viniciusfbb** [comment]
Fixed in our new release [3.4.1](https://github.com/skia4delphi/skia4delphi/releases)
