### ISSUE TITLE
Fonts in the device documents folder not loading on Android

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [skia4delphi/skia4delphi#143]
When replacing the FMX engine with Skia (GlobalUseSkia:=True), if you use a custom font which is deployed into the device documents folder, it isn't loaded by Skia but was by FMX.

This seems to be ok for iOS builds but not Android.

1. Create an empty app. Set GlobalUseSkia:=True in the project source file as per the instructions in the readme
2. Drop a standard TLabel onto the form (not an TSkLabel)
3. Set the Font.Family to the name of your custom font.
4. Add the custom font file to the Deployment options for the app (Android), targeted to the internal documents directory (./assets/internal for Android, or StartUp/Documents for iOS)
5. Run the app on the device.

Note that the font isn't used. This is more obvious when using icon files such as FontAwesome.

If you set GlobalUseSkia:=False so the app is using FMX engine, it shows the font without a problem.

Note: This was a bug in Delphi too until 10.4 when it was fixed.

We use custom fonts extensively through our app (icon fonts) so this is a blocker for using Skia4Delphi in our productions app. This is a real shame as it's the only issue we've found, and is otherwise excellent!

If there's a workaround, or a patch that would be fantastic.

**Comment by viniciusfbb** [comment]
Hi @MyBuzzTechnologies, thank you very much to report the issue.

If the FMX behaves this way, then we must adapt Skia to behave the same way.

Until the next release arrives, you can make a simple code adaptation in your project:

```delphi
uses
  System.IOUtils,
  Skia.FMX;

procedure TForm1.FormCreate(Sender: TObject);
begin
  {$IF DEFINED(ANDROID) OR DEFINED(IOS)}
  for var LFileName in TDirectory.GetFiles(TPath.GetDocumentsPath, '*.ttf', TSearchOption.soTopDirectoryOnly) do
    TSkTypefaceManager.RegisterTypeface(LFileName);
  {$ENDIF}
end;
```

**Comment by MyBuzzTechnologies** [comment]
Thank you, that's such a fast response and really appreciated.
I'll implement that change as a workaround.

**Comment by viniciusfbb** [comment]
Analisei melhor este caso e considero que não há nada a alterar em nosso sistema.

O Firemonkey não carrega fontes custons no Android, o que existe é algumas customizações existentes na internet para aplicar no "FMX.FontGlyphs.Android.pas" para tornar isso possível e algumas delas procuram na pasta TPath.GetDocumentsPath, mas não é código oficial. https://quality.embarcadero.com/browse/RSP-16741
