### ISSUE TITLE
Problemas ao habilitar o Skia em meu projeto.

### ISSUE THREAD

**Issue by amadeujunior18** [skia4delphi/skia4delphi#147]
Bom dia, primeiramente parabéns pelo projeto esta incrível.
Fiz um projeto simples com usando skia e deu certo, mais quando fui habilitar ele no projeto principal ele esta travando na tela de Splash quando ativo o " GlobalUseSkia := True;" .

**Comment by viniciusfbb** [comment]
Hi @amadeujunior18, thank you very much to report this issue!

There are 2 different settings to start using the Skia4Delphi and I think you skip the first one:

1. (Required) Enable your project to use any Skia code:

    - Inside the IDE with your project open, right click on your project and click "Enable Skia".

2. (Optional) Enable Skia to render your app overriding the default FMX system that draws all controls:

    - Open your project's dpr
    - Add Skia.FMX in uses
    - Add after "begin" the line: "GlobalUseSkia := True;"

**Comment by amadeujunior18** [comment]
já tinha feito esse procedimento.



![image](https://user-images.githubusercontent.com/6089726/185641852-70f09b7d-2f06-4acd-aa49-5521b762bb76.png)


![image](https://user-images.githubusercontent.com/6089726/185642232-3001b421-2495-4c64-803c-d3ce4e8c5305.png)

**Comment by viniciusfbb** [comment]
@amadeujunior18 

O problema acontece em um app em branco ou apenas neste projeto? Se for apenas neste projeto, quais libs terceirizadas você utiliza nele? Por acaso utiliza o Alcinoe?

Outras instruções:

1. É importante dar Clean no projeto, pelo menos 1 vez após essa habilitação: botão direito no projeto > Clean.

2. Certifique-se também de que você esteja compilando para a plataforma correta. Uma aplicação compilada para Android 32 pode rodar normalmente em um OS Android 64, mas não é o correto e isso trará problemas para carregar o Skia.

Nota: Você deve observar o OS do device e não o hardware pois existem devices com CPU 64 bits rodando Android 32 bits, e neste caso você deve selecionar Android 32 bits no projeto. Se você tem dúvida sobre o seu device, pode usar este app https://play.google.com/store/apps/details?id=com.finalwire.aida64

**Comment by amadeujunior18** [comment]
Show vini, deu certo colocando o componente em tela e desativando o GlobalUseSkia := True;

**Comment by amadeujunior18** [comment]
![WhatsApp Image 2022-08-19 at 14 49 20](https://user-images.githubusercontent.com/6089726/185678623-f99b496d-6709-480b-a48e-05e9f97d9cef.jpeg)

**Comment by viniciusfbb** [comment]
Perfeito! Então não tem a ver com o seu Android e nem com as configurações do Skia no seu projeto. Então agora resta saber mais sobre o que você usa neste projeto que não está permitindo a ativação do Skia como renderizador do seu app, que é o recurso mais interessante do Skia4Delphi...

Quais bibliotecas terceirizadas você está usando neste projeto? Por acaso você usa o Alcinoe?

**Comment by amadeujunior18** [comment]
Não sei te informa todas, mais eu uso o RestDataWare, ISComponents(do Jaques) e só
tem aqui o (FMX.ISAlcinoe), do ISComponents

**Comment by viniciusfbb** [comment]
O problema é este. Aparentemente o IS utiliza o Alcinoe internamente e isso é um problema pq o Alcinoe até então é a única biblioteca que não é compatível com o Skia pois ele faz vários hardcast de TCanvas para TCanvasGpu sendo que o Skia4Delphi tem seu próprio canvas que não é descendente do TCanvasGpu e então dá acess violation. Eu já abri um issue lá mas há muito tempo que o projeto já não tem mais suporte.

Há um tempo atrás o Jaque havia me dito que iria passar a usar o Skia no IS, então talvez em breve o Alcinoe seja removido do IS e você possa usar o Skia como renderizador do seu app.

Por enquanto não há nada que se possa ser feito (o erro é no código do Alcinoe e não no Skia). Você poderá utilizar toda a biblioteca do Skia4Delphi, incluindo APIs, controles, mas não o renderizador (GlobalUseSkia := True;).
