### ISSUE TITLE
Draw curved text

### ISSUE THREAD

**Issue by DonkeySmall** [skia4delphi/skia4delphi#154]
Hi, is there a way to draw text on a curve using Skia?

![textsonpath](https://user-images.githubusercontent.com/66531939/190390101-d94b0dfa-29eb-4969-bfba-9d774beb0110.png)

**Comment by viniciusfbb** [comment]
Not that I know. Using 1 letter instead of a text I know it's possible, see: https://stackoverflow.com/a/72586939/2614619

**Comment by DonkeySmall** [comment]
Thanks
