### ISSUE TITLE
TSkPaintBox import a PNG file (LoadfromFile / SaveToFile missing)

### ISSUE THREAD

**Issue by maurobotta** [skia4delphi/skia4delphi#156]
Hi

How i can to load a PNG in a  TSkPaintBox like LoadfromFile / SaveToFile ?

Load and save / export.

Thank you :)

**Comment by viniciusfbb** [comment]
Hi @maurobotta

Take a look in this sample: https://gist.github.com/viniciusfbb/0adbed0f95f2d9cff245a3e209d2a2f0

It basically loads a png and apply a resize and translation (offset) to make a "Fit and Crop" effect.
It also draws the image with rounded corners, but if you don't want it, just remove the lines of the rouded clip:

```delphi
//  ACanvas.Save;
//  try
//    ACanvas.ClipRoundRect(TSkRoundRect.Create(ADest, 48, 48), TSkClipOp.Intersect, True);
    DrawImageFitCrop(ACanvas, ADest, LImage);
//  finally
//    ACanvas.Restore;
//  end;
```

**Comment by viniciusfbb** [comment]
I forgot to show you the SaveToFile example. I made a simple code for you to understand:

```delphi
  var LSurface: ISkSurface := TSkSurface.MakeRaster(200, 200);
  // Draw here using the LSurface.Canvas
  // You can also call the SkPaintBox.OnDraw event:
  // SkPaintBox1Draw(nil, LSurface.Canvas, RectF(0, 0, 200, 200), 1);
  LSurface.MakeSnapshoot.EncodeToFile('a.png');
```

You can also ask quick questions on our telegram channel: https://t.me/skia4delphi

**Comment by viniciusfbb** [comment]
I will close it but few free to open a new one if you have more questions.
