### ISSUE TITLE
[3rd Party Demo] A cool 'Space Computer' demo of Skia4Delphi by Ian Barker!

### ISSUE THREAD

**Issue by edwinyzh** [skia4delphi/skia4delphi#16]
Need not to say Skia4Delphi  is a great project, but since it's new there are not much examples yet. And today I discovered one which is very cool with animated effects!
It's by Ian Barker who is a EMBT MVP.
[checkdigits/spacecomputer](https://github.com/checkdigits/spacecomputer)

**Comment by checkdigits** [comment]
I think it's pretty cool - but then I'm biased! 😉


![delphi_con_barker_demo](https://user-images.githubusercontent.com/2126394/142254921-df597889-8e5f-4c99-9ddd-7d72ead0bb48.gif)

The official conference page is here: https://delphicon.embarcadero.com/talks/move-your-ui-to-the-23rd-century-building-a-data-dashboard-with-delphi-and-skia-engage/

I will try and make the original video available to the Skia4Delphi team at some point.

(I'm tagging @viniciusfbb, @paulocesarbot and @renanborgez on this message for visibility).

**Comment by checkdigits** [comment]
Ah - the YouTube replay video is here: https://www.youtube.com/watch?v=jWP5oeEHyh0

**Comment by viniciusfbb** [comment]
Fantastic presentation! It could not have been better. 👏🏻👏🏻👏🏻

I would like to add the link to the demo and the presentation in the next commit, if you allow me of course.

Again, congratulations Ian Barker(@checkdigits)! The best presentation of the conference 😉

**Comment by checkdigits** [comment]
Thanks, all I did is show the hard work you guys put in. 😃 

I'm happy for you to add the links and use them any way which works for you. 👍

**Comment by viniciusfbb** [comment]
Added to documentation!
