### ISSUE TITLE
MakeImageSnapshot.EncodeToFile extremely slow when JPEG

### ISSUE THREAD

**Issue by peardox** [skia4delphi/skia4delphi#160]
Any way I can speed it up?

Like libjpeg for example?

**Comment by peardox** [comment]
Sorry - wrong problem (I always think jpeg is the issue). It's actually slow rendering into CPU from the Shader (code you gave nme a while back)
![image](https://user-images.githubusercontent.com/1549219/192843810-a8f2cb4f-ff08-42a0-b5ae-1abd407ac5f1.png)
So the png was slow
![image](https://user-images.githubusercontent.com/1549219/192843954-e17aeb34-7b04-419a-bed6-0563b4b87330.png)
And the jpg was OK

So it's actually this that's killing my stuff...

`  if (Self.Canvas is TGrCanvasCustom) and Assigned(TGrCanvasCustom(Self.Canvas).Context) then
    LSurface := TSkSurface.MakeRenderTarget(TGrCanvasCustom(Self.Canvas).Context, False, TSkImageInfo.Create(AWidth, AHeight))
  else
    LSurface := TSkSurface.MakeRaster(AWidth, AHeight);
  LSurface.Canvas.Clear(TAlphaColors.Null);

  if Assigned(Container) and (Container.ChildrenCount > 1) then
    begin
      for IDX := 0 to Container.ChildrenCount - 1 do
        begin
          if Assigned(Container.Children[IDX]) and (Container.Children[IDX] is TLayerShader) then
            begin
              var ThisLayer: TLayerShader := Container.Children[IDX] as TLayerShader;
              ThisLayer.OnDraw(ThisLayer, LSurface.Canvas, RectF(0, 0, AWidth, AHeight), 1);
            end;
        end;
    end;
` 

Not a lot I can do about that...

Not got anything simple - it's used as part [of something bigger](https://github.com/peardox/Lartis)

Windows [release version](https://peardox.itch.io/lartis)

**Comment by viniciusfbb** [comment]
Slowness occurs when drawing shader on a surface raster (CPU). Please put a breakpoint in the line `LSurface := TSkSurface.MakeRaster(AWidth, AHeight);` and check if the code is executing it.

**Comment by peardox** [comment]
Thanks @viniciusfbb - that made it obvious what was going wrong si its nice + speedy now
