### ISSUE TITLE
link with runtime package will cause exe file not run

### ISSUE THREAD

**Issue by mitchellhu** [skia4delphi/skia4delphi#163]
Delphi version 10.4 update 2
skia version :Skia4Delphi-3.4.1

project option\Packages\Runtime Packages\link with runtime packages check = true
the exe file run under IDE is fine.
but your run it directly on the folder, exe file will raise an error, not found 
 Skia.Package.RTL270.bpl
 Skia.Package.VCL270.bpl
how to solve this problem?
if set the link with runtime package check = False, it will be fine,
but I need the run other BplFroms, link runtime package will be set to true;

**Comment by viniciusfbb** [comment]
Fixed in [new release v4.0.0](https://github.com/skia4delphi/skia4delphi/releases)
