### ISSUE TITLE
IOS Simulator ARM64 build

### ISSUE THREAD

**Issue by paulohostert** [skia4delphi/skia4delphi#164]
Will it be compatible for compilation on IOS Simulator ARM64?

Today this error occurs:
[DCC Error] ld: in C:\Users\paulo\Documentos\Embarcadero\Studio\22.0\CatalogRepository\Skia4Delphi-3.4.1\Binary\iOSDevice64\Release\sk4d.a(sk4d.gr4d_backendsurface.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

**Comment by viniciusfbb** [comment]
Hi, thanks for reporting the issue!

We are already working on it and it will be added in the next version soon.

**Comment by viniciusfbb** [comment]
Added support in [new release v4.0.0](https://github.com/skia4delphi/skia4delphi/releases)
