### ISSUE TITLE
Undeclared identifier error 

### ISSUE THREAD

**Issue by Linuxuser1234** [skia4delphi/skia4delphi#167]
I m getting a Undeclared Identifier error For TSkTypefaceManager and RegisterTypeface 
`initialization
 TSkTypefaceManager.RegisterTypeface('C:\Boltgui\Popups\Font\DSEG14ClassicMini-Bold.ttf');
end.` 
![Screenshot 2022-11-02 074813](https://user-images.githubusercontent.com/67390756/199493656-b89e85fe-242a-4ef9-9403-bc90368a54db.png)

**Comment by viniciusfbb** [comment]
Hi! You need to add Skia unit to the uses.

**Comment by viniciusfbb** [comment]
Don't forget to enable Skia as your app's renderer to use the custom font in all controls, like TLabel, or TButton: https://github.com/skia4delphi/skia4delphi#enable-canvas
