### ISSUE TITLE
App modelo com erro no Android

### ISSUE THREAD

**Issue by GlaidsonPezavento** [skia4delphi/skia4delphi#17]
Olá, instalei o Skia4Delphi pelo executável e tentei compilar no meu Android 11, mas está ocorrendo erro e o app não executa como pode ser visto no print em anexo.

Existe algo que eu tenha que configurar para que ele execute?

![Erro Skia4Delphi](https://user-images.githubusercontent.com/20629304/142644013-3acad74f-4788-4441-8a3b-acefaeb96b7e.jpg)

**Comment by viniciusfbb** [comment]
Olá @GlaidsonPezavento! Obrigado por reportar o problema.

Verifique se você está compilando para o android correto, isto é, 32 ou 64 bits. Você pode usar o aplicativo SysCheck para verificar se o seu dispositivo é ARM64 (64 bits) ou ARM32 (32 bits). Inclusive seria bom você mandar a print do resultado do SysCheck.

**Comment by GlaidsonPezavento** [comment]
Obrigado @viniciusfbb pelo retorno, eu compilei em Android64 em modo Debug e Release, ambos apresentaram o mesmo comportamento.

Durante a instalação, a única modificação que fiz foi alterar a pasta de instalação padrão para uma pasta específica que tenho meus componentes, isto poderia gerar algum problema?

**Comment by viniciusfbb** [comment]
> Durante a instalação, a única modificação que fiz foi alterar a pasta de instalação padrão para uma pasta específica que tenho meus componentes, isto poderia gerar algum problema?

Não há problema.

> Obrigado @viniciusfbb pelo retorno, eu compilei em Android64 em modo Debug e Release, ambos apresentaram o mesmo comportamento.

Ta bem, você testou no Android64. Mas você testou no Android32? Digo isso porque pode ser que o seu celular seja Android32, então se você compilar para Android64 o app irá crashar na abertura.

**Comment by GlaidsonPezavento** [comment]
Creio que não será isto, pois meu aparelho é um S20 FE e é 64 bits.

**Comment by viniciusfbb** [comment]
Correção: Alterar a pasta de destino da instalação pode gerar problemas quando você coloca em uma pasta que exige permissão de administrador sem ter o executado o instalador com permissão de administrador. Por isso que o diretório padrão de instalação é na pasta de documentos do usuário (que não exige executar o instalador como administrador).

Se for este o caso, aconselho a desinstalar e instalar na pasta default, ou desinstale e execute como administrador (para instalar em outras pastas)

**Comment by viniciusfbb** [comment]
> Creio que não será isto, pois meu aparelho é um S20 FE e é 64 bits.
Provavelmente. Mas eu não te dou certeza porque até hoje fabricam muitos celulares com Android32 por ser mais leve. Então todos os celulares com menos memória RAM vêm com Android32 (a linha A da samsung, por exemplo, ou mesmo celulares da LG).

**Comment by GlaidsonPezavento** [comment]
@viniciusfbb Ocorre o seguinte:

Em minha máquina tenho as versões 10.3.3, 10.4.2 e 11.

Inicialmente eu havia instalado para para todas as versões, mas, eu havia mudado o local de instalação e não havia executado o instalador em modo administrador.

Então desinstalei tudo e instalei somente para o Delphi 11, não funcionou, o app deu erro;

Desinstalei novamente e reinstalei somente para o 10.4.2 em modo administrador e na pasta default do instalador, compilei e agora sim o app funcionou.

Nos primeiros testes eu somente esta utilizando Delphi 11 e não funcionava, provavelmente existe alguma incompatibilidade com o Delphi 11.

**Comment by viniciusfbb** [comment]
Ah sim, então o problema foi na instalação mesmo. Depois tenta com o delphi 11 de novo, porque é totalmente compatível (inclusive é o que eu uso aqui). Aí você tenta dessa última forma, desinstalando e instalando como administrador usando a pasta padrão.

**Comment by GlaidsonPezavento** [comment]
Eu consegui utilizar o Skia no Delphi 11, abri um novo projeto e adicionei todas as units do sample do Skia4Delphi, com isto consegui utilizar o sample em sua totalidade.

Mas, o sample original do Skia4Delphi não abriu compilando no Delphi 11.

Estou testando o Skia4Delphi e estou gostando, parabéns pelo projeto.

**Comment by viniciusfbb** [comment]
Ótimo! Vou verificar o que pode estar acontecendo.

Muito obrigado 👍🏻

**Comment by erivansilva** [comment]
Boa noite.

Não sei se é o caso, mas acredito que seja algo parecido. Eu estou fazendo alguns teste, e notei que em versões mais antigas do Android temos um problema.

Eu testei nas versões Android: 6.0.1, 7.1.2, 10 e 10 QKQ. obtive sucesso apenas nas versões 10.

![Skia4Delphi-AndroidAntigo](https://user-images.githubusercontent.com/69176863/145285969-403e09ec-38ec-4f80-8c55-eefa22dcfb00.png)

Atenciosamente.

**Comment by viniciusfbb** [comment]
@erivansilva De fato há um problema no carregamento da biblioteca no Android. Eu relatei inicialmente neste issue https://github.com/viniciusfbb/skia4delphi/issues/11

Não sei dizer exatamente em quais dispositivos ocorre, mas parece estar mais relacionado à fabricantes do que versões do Android (tenho aqui versões do Android 6, 8.0, 8.1 e 10 funcionando normalmente exceto no 6).

De toda forma já estamos trabalhando na solução, e será incluído na versão 3.0 ainda neste mês.

**Comment by viniciusfbb** [comment]
The problem was solved in new release. Please download new version 3.0.0.
