### ISSUE TITLE
DLL Question

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [skia4delphi/skia4delphi#170]
I created a DLL and there is no option to enable Skia -- is this a technological limitation or a design oversight.  If the latter, is there a way to "manually" enable it without having the normal **Enable Skia** option?

**Comment by viniciusfbb** [comment]
I will enable the menu to dlls too. But until then, just copy the sk4d.dll to the same directory as your dll (on Windows, "Enable Skia" does only that)

**Comment by viniciusfbb** [comment]
Added in the [new release v4.0.1](https://github.com/skia4delphi/skia4delphi/releases)
