### ISSUE TITLE
Skia text rendering issue in Android (FMX)

### ISSUE THREAD

**Issue by Sniperxx** [skia4delphi/skia4delphi#174]
Hello,
I'm having some sort of weird problem after using Skia in my project.
When enabling Skia and after drawing some text (Test Text, Hello World) in a VirtualListView
that text will appear like this:
Test Tex...
Hello wor...
Why there is some dots at the end of text?
And why the rest letters of the text is not finished but replaced with dots?
I'm missing something?

Compiling the project in Windows 32/64 is working fine
but this problem persists in any Android build Debug/Release.

I've managed to temporary fix this issue by declaring the 
ksVirtualListView before the Skia.FMX in the Uses list (Inside the project file)

program ExampleApp;

uses
  System.StartUpCopy,
  ksVirtualListView,
  Skia.FMX,
  FMX.Forms,
....
Drawing the text is now fine but the program started being slower, buggy and crashes sometimes!!
Any solution is appreciated.
thanks in advance.

**Comment by viniciusfbb** [comment]
@Sniperxx The PentireFMX lib was doing a wrong initialization. I made the fix/pull request to allow custom renders. Can you apply the changes from your source and give us feedback?

Pull request with the fix: https://github.com/gmurt/PentireFMX/pull/10

**Comment by viniciusfbb** [comment]
I will close due to lack of feedback and because it is likely to have been resolved with my pull request, but feel free to continue sending messages in this topic and I can reopen it again.
