### ISSUE TITLE
Add virtual method TextChanged in TSkLabel

### ISSUE THREAD

**Issue by havrlisan** [skia4delphi/skia4delphi#182]
Currently, there are 2 methods called on the text and text settings change: `TextSettingsChanged(Sender)` and `WordsChange(Sender)`. Both of these are in the strict private section, while they should be (or at least the latter one) in the protected section, and marked as virtual.

The reason for this is that you have no way of knowing when the Words collection has changed.

**Comment by havrlisan** [comment]
In addition to mentioned, you should also make the method
`function NormalizeParagraphText(const AText: string): string;`
a virtual method instead. Currently, it is a nested method within `function TSkLabel.GetParagraph: ISkParagraph;`.

This will allow the manipulation of text just before it is rendered, for example making all the text uppercase etc.

**Comment by viniciusfbb** [comment]
Added in last release ([v4.1.0](https://github.com/skia4delphi/skia4delphi/releases))
