### ISSUE TITLE
Error appIOS Simulator ARM

### ISSUE THREAD

**Issue by paulohostert** [skia4delphi/skia4delphi#186]
When we enable skia in the project and compile it for IOS Simulator ARM, the app in the simulator closes without showing any error after starting.
We created a new project in delphi and compiled it in the simulator for IPhone 14 with IOS 16 and it worked correctly. The problem only occurs after enabling skia in the project.

**Comment by viniciusfbb** [comment]
What version of your Skia4Delphi? In the Skia.pas you will find the version.

**Comment by paulohostert** [comment]
I installed version 4.0.2 just before creating the new project.
<img width="320" alt="image" src="https://user-images.githubusercontent.com/94071196/205519823-608d44a3-dcf9-4e6f-904d-b00afd2626ee.png">

**Comment by paulohostert** [comment]
@viniciusfbb , we have some temporary alternative that we can use here?

**Comment by viniciusfbb** [comment]
@paulohostert Problem confirmed! There are no workarounds, we'll have to change the binaries for static loading. This fix will be available in the next release in a few weeks.

**Comment by paulohostert** [comment]
Hi, do you have a release date?

**Comment by viniciusfbb** [comment]
Fixed in last release ([v4.1.0](https://github.com/skia4delphi/skia4delphi/releases))
