### ISSUE TITLE
freezing application on destroy after enabling GlobalUseSkia

### ISSUE THREAD

**Issue by mahmoudikia** [skia4delphi/skia4delphi#187]
Hi, I have an windows application that have mixed vcl and fmx using FiremonkeyContainer.
and in the fmx form, i set GlobalUseSkia to true and GlobalUseSkiaRasterWhenAvailable to false.
rendering performs well, but after closing the app and main vcl form is freezed and IDE stays in Debug mode.

what can i do?

**Comment by viniciusfbb** [comment]
Hi! Thank you very much for reporting the problem.

I installed TFiremonkeyContainer in Alexandria 11.2 and I am not able to simulate the problem.

![image](https://user-images.githubusercontent.com/11139086/207364939-f42f7657-066f-454b-a604-7eb89ddf58b6.png)

Can you provide a minimal project that reproduces the problem?

**Comment by viniciusfbb** [comment]
Fixed in our new release [v5.0.0](https://github.com/skia4delphi/skia4delphi/releases)
