### ISSUE TITLE
Show a warning message if the SKIA DLL (sk4d.dll) cannot be found

### ISSUE THREAD

**Issue by PeterPanino** [skia4delphi/skia4delphi#189]
I am using Skia4Delphi 4.0.2 in Delphi 11 VCL. Currently, when the sk4d.dll cannot be found, the app crashes in **Skia.API.SkInitialize**. It would be nice if an explicit warning message "sk4d.dll not found" would be displayed instead.

**Comment by viniciusfbb** [comment]
@PeterPanino Thank you very much for your suggestion.

This issue already exists, so only the oldest will be kept.

Duplication of issue #130
