### ISSUE TITLE
Not an issue just a TSKPaintbox question

### ISSUE THREAD

**Issue by DaveMoss69** [skia4delphi/skia4delphi#191]
I'm learning to use the Skia package, thank you for the hard work involved in making this.
I have a question about accessing, or passing the canvas, TRect etc of the vcl TSKpaintbox component to another
unit function, but not passed from the onDraw event.
This function will do all the drawing and save a PNG but also draw on the vcl component.
I may draw several images and later choose which image to show in the paintbox.

I would then like to use a button to choose which of the created png's to show on the component.
Hope this makes sense.  Or am I thinking about this the wrong way?

Cheers
Dave

**Comment by viniciusfbb** [comment]
Hi Dave!

TSkPaintBox was made just for drawing on the screen using Skia. If you want to draw images using Skia, that is, without showing it to the user on the screen, the most appropriate would be to use Bitmap.SkiaDraw(), which then you will draw in a TBitmap using Skia. See an example: https://github.com/skia4delphi/skia4delphi#bitmap
Note: You will need to add to the uses the units: Skia and Skia.Vcl.

You can also ask quick questions on our telegram channel: https://t.me/skia4delphi

**Comment by DaveMoss69** [comment]
Really appreciate the prompt reply and the example,
looks like that's what I need.
Thank you!

**Comment by viniciusfbb** [comment]
@DaveMoss69 Just an extra tip: You can also use the Skia apis directly, without use the TBitmap. For that use the SkSurface:

```delphi
  var LSurface: ISkSurface := TSkSurface.MakeRaster(100, 100);
  LSurface.Canvas.xx
  LSurface.MakeImageSnapshot.EncodeToFile('a.png');
```

**Comment by DaveMoss69** [comment]
Hello Vinicius,
I have come back to this project and now need to change the origin of the LSurface from the top left to any of the other corners.  How would you suggest doing this please?

**Comment by viniciusfbb** [comment]
I didn't understand well the question, but if you want to draw on canvas on X, Y position, you can call Canvas.Translate(X, Y), but you should save and restore later to rollback that translate operation because after the Canvas.Translate(X, Y), all draw calls will have that (X, Y) offset. For example:
```delphi
  var LSurface: ISkSurface := TSkSurface.MakeRaster(100, 100);
  LSurface.Canvas.Save;
  LSurface.Canvas.Translate(X, Y);
  LSurface.Canvas.xx
  LSurface.Canvas.Restore;
  LSurface.MakeImageSnapshot.EncodeToFile('a.png');
```

**Comment by viniciusfbb** [comment]
If you want to do an offset, then use Canvas.Translate(X, Y). If you want to invert the coordinates reference, you could use Canvas.Scale(-1, 1) for example to invert the follow draws horizontally (you may call Canvas.Translate also I guess.

**Comment by viniciusfbb** [comment]
Simple example:
[DrawFlipped.zip](https://github.com/skia4delphi/skia4delphi/files/13033036/DrawFlipped.zip)
