### ISSUE TITLE
Drawing Text Centered in TSkLabel?

### ISSUE THREAD

**Issue by Sniperxx** [skia4delphi/skia4delphi#193]
Hello,
Trying to draw centered text inside of TSkLabel but with no success
  ```
procedure DrawExample(const ACanvas: ISkCanvas; LRect: TRectF);
  var
    LFont: ISkFont;
    LPaint: ISkPaint;
    RS : TResourceStream;
  begin
    RS := TResourceStream.Create(HInstance, 'Fontx', RT_RCDATA);
    try
      LFont := TSkFont.Create(TSkTypeface.MakeFromStream(RS, 0));
      LFont.Size := 14;
      LPaint := TSkPaint.Create;
      LPaint.Color  := $FFFFFFFF;
      ACanvas.DrawSimpleText('Example Text', (LRect.Width /2), LRect.Top+(LRect.Height /2), LFont, LPaint);
   finally
      RS.Free;
    end;
  end;
```
```
procedure TForm1.SkLabel1Draw(ASender: TObject; const ACanvas: ISkCanvas;
  const ADest: TRectF; const AOpacity: Single);
begin
 DrawExample(ACanvas, ADest);
end;
```
Thanks in advance.

**Comment by viniciusfbb** [comment]
Hello @Sniperxx 

Why exactly do you need it? You can use custom fonts normally in TSkLabel without code. In fact, you need just register the custom font with Skia API at initialization:

```delphi
uses
  Skia.FMX;

initialization
  TSkDefaultProviders.RegisterTypeface(TPath.Combine(TPath.GetDocumentsPath, 'Lato.ttf'));
```

Then, all TSkLabel can use that font. And, when you use the Skia4Delphi render ("GlobalUseSkia := True;" in dpr), all controls can use that custom font also, even the TLabel or TButton or any other.
This code works on all platform and you can also load the ttf from stream.

But, if you want to draw texts using code, using the Skia API, the easiest way is to use the class TSkTextLayout in unit Skia.FMX.Graphics, which have the properties HorizontalAlign and VerticalAlign, and much more.

**Comment by Sniperxx** [comment]
Thanks [viniciusfbb](https://github.com/viniciusfbb) this fixed my problem
```
   RS : TResourceStream;
begin 
  RS := TResourceStream.Create(HInstance, 'Fontx', RT_RCDATA);
  Try
    TSkDefaultProviders.RegisterTypeface(RS);
  finally
    RS.Free;
  end;
```
