### ISSUE TITLE
Rodando aplicação em win 32 bits

### ISSUE THREAD

**Issue by kellyCardosoS** [skia4delphi/skia4delphi#195]
![image](https://user-images.githubusercontent.com/54945485/210787646-89597e9e-9ada-40dc-b93a-6f8af0d5c928.png)
I'm developing a software in delphi VCL that needs to run on win32 bits, but I come across this error.
I performed a test without using skia components and it works correctly.
Any solution for the problem?

**Comment by viniciusfbb** [comment]
Qual a versão do seu Windows?

**Comment by kellyCardosoS** [comment]
XP

**Comment by viniciusfbb** [comment]
O Skia suporta apenas o Windows 7+

**Comment by viniciusfbb** [comment]
Assim como o RAD Studio, oficialmente, da suporte apenas ao Windows 7+
https://docwiki.embarcadero.com/PlatformStatus/en/Main_Page

**Comment by kellyCardosoS** [comment]
Entendo, obg pelo retorno
