### ISSUE TITLE
D10.2.3

### ISSUE THREAD

**Issue by limelect** [skia4delphi/skia4delphi#198]
I could not install the new version
For some reason the old tab stayed there EMPTY as a reminder.
When i tried to revert to my old BPL now i cannot load it access violation
Any help.?
Trying to install the new i get abort. Compilation is OK

**Comment by viniciusfbb** [comment]
Hi @limelect. Thank you very much for reporting the issue!

> For some reason the old tab stayed there EMPTY as a reminder.

Can you explain it better? Do you have a print screen?
If an error occurs during installation, the setup opens the logs in notepad automatically. If this has happened, please send us the log files.

Maybe it's a conflict with some old version installed. For a secure installation, follow these steps:

1. Install running the setup (the manual installation is not recommended) with the IDE closed. You can choose always the same destination folder (prefer the default folder to avoid administrator permission), even if there is an old installation there.
2. Delete old Skia4Delphi folders that you detect on your computer.
3. Check in your "RAD Studio > Options > Language > Delphi > Library > Library Path >" if there is any other skia directory besides these:
![image](https://user-images.githubusercontent.com/11139086/215127012-f0a5ddb2-f695-4647-bfe4-6b4fe1486f06.png)
4. Check in your "RAD Studio > Component > Install Package" if there is any other skia package besides these:
![image](https://user-images.githubusercontent.com/11139086/215127048-cf53705d-09c2-41d7-869f-6366fd1cb2db.png)

**Comment by viniciusfbb** [comment]
Ps: A common problem that automatic installers face is in relation to the libraries that use it. If you have any libraries that use Skia4Delphi, uninstall them before installing a new version using the installer.

**Comment by limelect** [comment]
Have a look here  https://en.delphipraxis.net/topic/8238-skia-component-and-ide
I did this by hand.
Now I used Skia4Delphi_3.3.2_Setup.exe and it works
However, can you include also **DEBUG** not only RELEASE ???
An notify me thanks
Is 3.3.2 is new I found it on my disk

**Comment by viniciusfbb** [comment]
Why do you want debug mode? The problem was solved? I can close this issue?
