### ISSUE TITLE
Error compilação unit Skia.API IOS Simulator ARM 4.1.0

### ISSUE THREAD

**Issue by paulohostert** [skia4delphi/skia4delphi#199]
![image](https://user-images.githubusercontent.com/94071196/215182064-79fc13b6-67a0-4d63-b16e-06df037c317a.png)

**Comment by paulohostert** [comment]
Fiz esse ajuste e funcionou!
![image](https://user-images.githubusercontent.com/94071196/215193377-154d5ea2-9faa-486f-8af4-842cf0e4d5f2.png)

**Comment by viniciusfbb** [comment]
Fixed in latest version: [v4.1.1](https://github.com/skia4delphi/skia4delphi/releases)
