### ISSUE TITLE
Access violation at address 7A117893 in module 'sk4d.dll'. Write of address 0E7A8000.

### ISSUE THREAD

**Issue by RamonSouza96** [skia4delphi/skia4delphi#201]
This error happens when opening the secondary form, which has the "transparency" property set to "true". When we try to adjust the size of the secondary form based on the size of the main form in the "OnShow" event of the secondary form, through the following code:

FrmSecundario.Width := FrmMain.Width;
FrmSecundario.Height := FrmMain.Height;

https://user-images.githubusercontent.com/34917070/217017299-01f8d603-3090-476b-bb80-43083291049a.mp4

**Comment by TheOriginalBytePlayer** [comment]
I am running into what sounds like this issue as well.  I have a form that's displaying a hardware accelerated rendering which is always on top, so I can't draw on it directly.  My solution was to create a transparent secondary form and parent it to the fist, so I can display a selection rectangle (and other things) on top of the render.  This had worked in prior Skia Versions but now doesn't display this secondary form at all, and creates an access violation in Skia.

I am attaching a simple project that demonstrates this:
[TransparentOverlayAV.zip](https://github.com/skia4delphi/skia4delphi/files/10866079/TransparentOverlayAV.zip)

**Comment by TheOriginalBytePlayer** [comment]
BTW, I downgraded to Version 3.4.1 and this issue went away so it's definitely an issue with Version 4.

**Comment by viniciusfbb** [comment]
Fixed in our new release [v5.0.0](https://github.com/skia4delphi/skia4delphi/releases)
