### ISSUE TITLE
Minor issue: the English uninstaller text has a grammatical error

### ISSUE THREAD

**Issue by checkdigits** [skia4delphi/skia4delphi#202]
When the installer runs it will uninstall any previous versions of Skia4Delphi if it finds them.

There is an grammatical error in the English uninstaller wording.

It says: "Uninstalling another versions"

It _should_ say: "Uninstalling other versions"

😃

**Comment by viniciusfbb** [comment]
Fixed in new release: [v4.1.1](https://github.com/skia4delphi/skia4delphi/releases)
