### ISSUE TITLE
IOS64 and IOS Sim64 deployment broken

### ISSUE THREAD

**Issue by Spelt** [skia4delphi/skia4delphi#205]
Hi 

I think the deployment of the skia files are not working anymore since 4.1.1.
The bins are not added to the deployment lists anymore. As far as I can tell it happens only for simulator and IOS64.

Using Skia 4.1.1 and Delphi 11.3.

Maybe someone can confirm this?

Thanks for this awesome lib.

**Comment by Spelt** [comment]
False alarm.

**Comment by viniciusfbb** [comment]
Yes. iOSDevice64 and iOSSimARM64 are static library. It mean that they don’t need to deploy nothing because the compiler achieves to put everything in the app, and in a smart way (just the features that are using)

**Comment by viniciusfbb** [comment]
Perhaps in the future this library will have other static platforms. It would be amazing.
