### ISSUE TITLE
SVG Incompatibilities solved

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [skia4delphi/skia4delphi#21]
I was having a lot of problems with SVGs produced by CorelDraw showing up as entirely black until I found 

https://github.com/sk1project/sk1-wx

which is an open source SVG editor which produces amazingly 100% compatible SVGs for Skia, including gradients and much more.  I would have posted this in your wiki but there isn't one and I thought I really should share this information.

**Comment by viniciusfbb** [comment]
Nice tip! I will add it to the documentation.

Thank you very much!

**Comment by viniciusfbb** [comment]
Added your suggestions in new release documentation.
