### ISSUE TITLE
Crashing when deleting edit's text on Android

### ISSUE THREAD

**Issue by viniciusfbb** [skia4delphi/skia4delphi#214]
A user reported an important exception when handling text in TEdit, in a basic project with a TSkLabel and TEdit. It adds text to the edit and when deleting the text the crash occurs.

https://user-images.githubusercontent.com/11139086/228579491-dc066469-e407-4783-846e-be1e92b83f9a.mp4

[android-text-issue.zip](https://github.com/skia4delphi/skia4delphi/files/11102237/android-text-issue.zip)

**Comment by GlaidsonPezavento** [comment]
I installed skia 4.1.1 and the problem persists, just enabling skia is enough to close the application as soon as I touch the button to delete the text

**Comment by GlaidsonPezavento** [comment]
![versão delphi](https://user-images.githubusercontent.com/20629304/228583636-977bb32f-05c8-4b79-b0c2-ead71364ea6a.png)
![SDK](https://user-images.githubusercontent.com/20629304/228583646-bec5568e-cf4c-4522-9301-3cabd43a5f0e.png)
![NDK](https://user-images.githubusercontent.com/20629304/228583649-783ec3d1-c20b-4039-ac3e-10cd19c7270b.png)
![java](https://user-images.githubusercontent.com/20629304/228583654-c615534b-ce76-453c-ad78-0afe216e965a.png)

I don't know if this information is so necessary, but here is the version of delphi and the SDK installed on my machine, at the moment I have skia 4.1.1
