### ISSUE TITLE
ISKCanvas remains nil on macOS 64

### ISSUE THREAD

**Issue by GitUserMarkus** [skia4delphi/skia4delphi#259]
I am trying to use the following code mostly found in the Skia4Delphi docs in order to use Skia features when drawing on a FMX bitmap.canvas:

  
      ABitmap := TBitmap.create(940,940);

      if ABitmap.Canvas.BeginScene then
      try

        LCanvas := TSkCanvasCustom(ABitmap.Canvas).Canvas;

        var LPaint: ISkPaint := TSkPaint.Create(TSkPaintStyle.Stroke);
         LPaint.StrokeWidth := 8;
         LPaint.AntiAlias := True;
         LPaint.Color := $FF4285F4;
         LPaint.StrokeCap := TSkStrokeCap.Round;

        LCanvas.DrawLine(TPointF.Create(1, 1),TPointF.Create(X, Y), LPaint);
      finally
        ABitmap.Canvas.EndScene;
      end;

However, LCanvas remains nil and thus an exception is fired when calling LCanvas.DrawLine.

Any idea what goes wrong? 
I am using Delphi 11.3 with Skia4Delphi 4.1.1 installed using GetIt package manager.

**Comment by GitUserMarkus** [comment]
No I did not since I dont want all the rendering to be done by Skia. My aim is to use Skia for a single Canvas only.

**Comment by viniciusfbb** [comment]
Ok, so you can't cast ABitmap.Canvas to TSkCanvasCustom, because the canvas implementations of bitmaps and screen will not be a skia class. But another option that works for both case (with or without skia render) is to use ABitmap.SkiaDraw, like this:

```delphi
uses
  Skia, Skia.FMX {or Skia.Vcl};

...

  var LBitmap := TBitmap.Create(100, 100);
  try
    LBitmap.SkiaDraw(
      procedure (const ACanvas: ISkCanvas)
      begin
        // Draw with Skia canvas...
      end);
```
