### ISSUE TITLE
Conflict with "unneccessary" TBitmap Helper

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [skia4delphi/skia4delphi#26]
The Issue:

Delphi only allows one helper for each object type so if you've created your own TBitmap Helper, as I have, then including Skia.FMX.pas will override that with the one if it comes later in the uses clause than the unit that contains your own bitmap helper.

As the functionality offered by the TSkBitmapHelper is so minimal I propose the following changes:

1. Remove the current TSkBitmapHelper (or at the very least wrap it in an $IFDEF) 
2. Replace it with a tskImageHelper which won't conflict with anything, and 
3. Add a separate SkiaDraw procedure that takes a bitmap as its first parameter

```delphi
{$IFDEF SKIA_BITMAP_HELPER}
  TSkBitmapHelper = class helper for TBitmap
  public
    procedure SkiaDraw(const AProc: TSkDrawProc; const AStartClean: Boolean = True);
    function ToSkImage: ISkImage;
  end;
{$ELSE SKIA_BITMAP_HELPER}

  TSkImageHelper = class helper for TSkImage
  public
    class function MakeFromBitmap(const inBitmap:TBitmap): ISkImage; static;
  end;

procedure SkiaDraw(ToBitmap:TBitmap; const AProc: TSkDrawProc; const AStartClean: Boolean = True);
{$ENDIF SKIA_BITMAP_HELPER}

implementation

class function TSkImageHelper.MakeFromBitmap(const inBitmap:TBitmap): ISkImage;
var
  LColorType: TSkColorType;
  LData: TBitmapData;
begin
  if (inBitmap=nil) or inBitmap.IsEmpty then
    raise ESkFMX.Create('Invalid bitmap');
  case InBitmap.PixelFormat of
    TPixelFormat.RGBA: LColorType := TSkColorType.RGBA8888;
    TPixelFormat.BGRA: LColorType := TSkColorType.BGRA8888;
  else
    raise ESkFMX.Create('Invalid pixelformat');
  end;
  if not Inbitmap.Map(TMapAccess.Read, LData) then
    raise ESkFMX.Create('Could not map the bitmap');
  try
    Result := TSkImage.MakeRaster(TSkImageInfo.Create(Inbitmap.Width, Inbitmap.Height, LColorType), LData.Data, LData.Pitch);
  finally
    Inbitmap.Unmap(LData);
  end;
end;

procedure SkiaDraw(ToBitmap:TBitmap; const AProc: TSkDrawProc; const AStartClean: Boolean);
var
  LColorType: TSkColorType;
  LImageInfo: TSkImageInfo;
  LSurface: ISkSurface;
  LData: TBitmapData;
begin
  if (ToBitmap=Nil) or ToBitmap.IsEmpty then
    raise ESkFMX.Create('Invalid bitmap');
  case ToBitmap.PixelFormat of
    TPixelFormat.RGBA: LColorType := TSkColorType.RGBA8888;
    TPixelFormat.BGRA: LColorType := TSkColorType.BGRA8888;
  else
    raise ESkFMX.Create('Invalid pixelformat');
  end;
  LImageInfo := TSkImageInfo.Create(ToBitmap.Width, ToBitmap.Height, LColorType);
  if ToBitmap.Map(TMapAccess.ReadWrite, LData) then
    try
      LSurface := TSkSurface.MakeRasterDirect(LImageInfo, LData.Data, LData.Pitch);
      if AStartClean then
        LSurface.Canvas.Clear(TAlphaColors.Null);
      AProc(LSurface.Canvas);
    finally
      ToBitmap.Unmap(LData);
    end;
end;

procedure TskCustomControl.paint; 
begin
...
{$IFDEF SKIA_BITMAP_HELPER}
    FBuffer.SkiaDraw(
{$ELSE SKIA_BITMAP_HELPER}
    SkiaDraw(FBuffer,
{$ENDIF SKIA_BITMAP_HELPER}
...

```

**Comment by viniciusfbb** [comment]
Hi @TheOriginalBytePlayer, I appreciate your feedback!

Class helper conflicts can really be a problem. However class helpers accept inheritance, so one of the many possible workarounds would be for your class helper to be a descendant of the skia class helper. For example:

```delphi
TBitmapHelper2 = class helper(TSkBitmapHelper) for TBitmap
   // ...
end;
```

However, I will accept the issue because the way it is is not ideal, we are planning to implement the helper in TCanvas instead of TBitmap in the next release.

**Comment by TheOriginalBytePlayer** [comment]
Thanks for the info, but might I respectfully suggest you implement the helpers in the skcomponents rather than in the native Delphi components?

Maybe I’m missing something, but having the bitmap compatibility in an skImage helper avoids any conflict and offers a consistency in term of the other MakeFromXXX options

  TSkImageHelper = class helper for TSkImage
  public
    class function MakeFromBitmap(const inBitmap:TBitmap): ISkImage; static;
end;

Similarly, if you add a helper to tskCanvas that take a TCanvas parameter rather than the other way around, it avoids any potential conflict while offering the same functionality.

**Comment by viniciusfbb** [comment]
We'll see a way that fits better

**Comment by TheOriginalBytePlayer** [comment]
I have full confidence – the library is amazing and I really appreciate it.  Would love some more samples – but I’m slowly figuring it all out.

**Comment by viniciusfbb** [comment]
Removing the TBitmap helper integrating with Skia breaks our code design. This is something you should work around in your code. My main suggestion is to use inheritance helper. The good news is that with the new version of Skia4Delphi, released now, you may use a lot less skia code, as now Skia4Delphi can be the default renderer of firemonkey, replacing Canvas of firemonkey.
