### ISSUE TITLE
TSkLabel.TCustomWordsItem OnClick

### ISSUE THREAD

**Issue by nemoinkognito** [skia4delphi/skia4delphi#262]
The TCustomWordsItem OnClick event can trigger sending an out of date argument to the OnClick event handler.
(Skia4Delphi 6.0.0-beta3 on windows, Delphi 11.3)

In my specific example the OnClick handler rebuilds the contents of the SkLabel. If the mouse is clicked again without moving the next OnClick event call will be called with a TCustomWordsItem that is no longer valid. It results in faulty data or an exception. I suspect that FWordsMouseOver is not updated if the mouse does not move. 

This solution works for me:
FMX.Skia row 5234

```delphi
procedure TSkLabel.Click;
var
  LClickedItem: TCustomWordsItem;
begin
  LClickedItem := GetWordsItemAtPosition(FClickedPosition.X, FClickedPosition.Y);
  if Assigned(LClickedItem) and (LClickedItem = GetWordsItemAtPosition(PressedPosition.X, PressedPosition.Y)) then
  begin
    TMessageManager.DefaultManager.SendMessage(Self, TItemClickedMessage.Create(LClickedItem));
    if Assigned(LClickedItem.OnClick) then
      //LClickedItem.OnClick(FWordsMouseOver)
      LClickedItem.OnClick(LClickedItem)
    else
      inherited;
  end
  else
    inherited;
end;
```

**Comment by viniciusfbb** [comment]
Fixed on latest version [v6.0.0-beta4](https://github.com/skia4delphi/skia4delphi/releases)
