### ISSUE TITLE
Bug with memo in Android

### ISSUE THREAD

**Issue by ETSPMeder** [skia4delphi/skia4delphi#267]
I just found out that there is an error on Android when you have skia enabled globally. Unfortunately I was not able to localize the error exactly. However, the error causes the entire application to close. In the Debugger I get a ERangeError Message.

But I have attached a sample project that can be used to reproduce the error. You only have to write test into the memo box until the error is triggered. approx. 20 - 30 words.

I use a Pixel 7a with Android 13 installed.
[BugInfoFrame.zip](https://github.com/skia4delphi/skia4delphi/files/12750522/BugInfoFrame.zip)

**Comment by viniciusfbb** [comment]
You are using the v5 or older that have some issues with texts. Could you try with our latest version [6.0.0-beta3](https://github.com/skia4delphi/skia4delphi/releases)?

**Comment by ETSPMeder** [comment]
@viniciusfbb Problem doesn't exist anymore.
I would like to take this opportunity to address 2 things.
1) Your response time to my request was really terrific. Outstanding!
2) Thanks for the work you put so far and still put into this project. I'm always excited when I see how much better delphi can look on mobile if you just use the right tools :-)
