### ISSUE TITLE
Skia library may be unloaded too soon

### ISSUE THREAD

**Issue by neslib** [skia4delphi/skia4delphi#27]
First of all, this Skia library is designed very well. Congratulations! I have created a Skia wrapper before using the SkiaSharp C API, but this one has more features. Impressive!

I small thing I encountered is that I get access violations on shutdown if I have custom FMX controls that contain a Skia object (like an `ISkCanvas`). In that case, the Skia library may be unloaded _before_ the custom FMX control is destroyed. That is, the `TSkiaApi.Destroy` class destructor is called _before_ `FMX.Forms.Finalization` is called. `FMX.Forms.Finalization` frees any forms and thus FMX controls. Then, when custom FMX control is destroyed, it will also destroy the Skia object. But because the Skia library has already been unloaded, this results in an access violation.

A workaround is to add the Skia.Api or Skia unit to the DPR as the _very first_ unit. That way, the class destructor gets called _after_ the FMX forms are destroyed. But it would be nice if this is not needed.

**Comment by viniciusfbb** [comment]
Hi @neslib! Thank you very much for reporting the issue. It is an honor that you are using our lib, we also really appreciate your work!

There really is this problem current version, and the easiest workaround is precisely to change the order in dpr as you said. For the next release we changed the Skia.FMX.pas to register an IFMXCanvasService service, to ensure that the library will not be unloaded before the UnregisterCanvasClasses of the firemonkey.

**Comment by viniciusfbb** [comment]
The problem was solved in new release. Please download new version 3.0.0.
