### ISSUE TITLE
Add more ISkParagraph features

### ISSUE THREAD

**Issue by neslib** [skia4delphi/skia4delphi#28]
Feature request: `ISkParagraph` does not expose all C++ `Paragraph` APIs. APIs that are currently missing are:

- getMinIntrinsicWidth
- getMaxIntrinsicWidth
- getAlphabeticBaseline
- getIdeographicBaseline
- getLongestLine
- didExceedMaxLines
- getGlyphPositionAtCoordinate (important)
- getLineMetrics
- lineNumber
- markDirty
- unresolvedGlyphs
- visit (not important)

In particular, I am missing then `getGlyphPositionAtCoordinate` API.

Adding these in a future version would be greatly appreciated.

**Comment by viniciusfbb** [comment]
@neslib We already added many features to the ISkParagraph in develpmet version (closed to plublic):

```delphi
  ISkParagraph = interface(ISkObject)
    ['{27462359-56C6-41DF-9D15-840E1DEC25C9}']
    function DidExceedMaxLines: Boolean;
    function GetAlphabeticBaseline: Single;
    function GetGlyphPositionAtCoordinate(const ADX, ADY: Single): TSkPositionAffinity;
    function GetHeight: Single;
    function GetIdeographicBaseline: Single;
    function GetLineMetrics: TArray<TSkMetrics>;
    function GetLongestLine: Single;
    function GetMaxIntrinsicWidth: Single;
    function GetMaxWidth: Single;
    function GetMinIntrinsicWidth: Single;
    function GetRectsForPlaceholders: TArray<TSkTextBox>;
    function GetRectsForRange(const AStart, AEnd: Cardinal; const ARectHeightStyle: TSkRectHeightStyle; const ARectWidthStyle: TSkRectWidthStyle): TArray<TSkTextBox>;
    procedure GetWordBoundary(const AOffset: Cardinal; out AStart, AEnd: Cardinal);
    procedure Layout(const AWidth: Single);
    procedure Paint(const ACanvas: ISkCanvas; const AX, AY: Single);
    function ToPath: ISkPath;
    property AlphabeticBaseline: Single read GetAlphabeticBaseline;
    property Height: Single read GetHeight;
    property IdeographicBaseline: Single read GetIdeographicBaseline;
    property LineMetrics: TArray<TSkMetrics> read GetLineMetrics;
    property LongestLine: Single read GetLongestLine;
    property MaxIntrinsicWidth: Single read GetMaxIntrinsicWidth;
    property MaxWidth: Single read GetMaxWidth;
    property MinIntrinsicWidth: Single read GetMinIntrinsicWidth;
  end;
```

Some features like ToPath are self-authored, there is no official skia. We also added a typeface provider that will register custom fonts for SkParagraph.

If you're planning on making some SkParagraph-based component or class, I have good news, we've made a TSkTextLayout class (descendant of TTextLayout) and a TSkLabel control (multiple color and style support), both using SkParagraph.

There being no more delays, in two weeks we will release the next release.

**Comment by viniciusfbb** [comment]
Exactly! In this version we want to better integrate with FMX, creating our own canvas and registering. It seems to be worth it as it has a chance of having performance gains because the skia has a lot of automatic internal cache system which is exactly what FMX lacks.

Except from text rendering, FMX has a relatively fast canvas, but the problem is that it doesn't have any cache system at all. For example, if you have an image on a control that is stretched, it will stretch every 60 fps of the render, losing performance.

At the current stage, we already have a working TSkCanvasRaster canvas that draws the entire fmx form with the CPU. As to be expected, the performance is not so good, but it will be useful for testing. The implementation using GPU is a little complicated, we've already started and we're still hitting the ideal design. Probably at first we will only use OpenGL so as not to postpone the release.

**Comment by PonyPC** [comment]
That's a remarkable thought. I'm expecting a significant performance improvement of firemonkey and implementing every component like flutter based on skia4delphi but still stuck at flutter layout 😂. Replacing the backend is a better solution.

**Comment by viniciusfbb** [comment]
@neslib We made the new TTextLayout based on SkParagraph and exposed many functions in SkParagraph. Check out our new version 3.0.0 and let us know what you think.

**Comment by viniciusfbb** [comment]
@neslib One feature I'm sure you'll really appreciate is the SkSL (Skia's Shader Language), which is used through SkRuntimeEffects. Currently it's hard to maintain shader codes supporting the various existing shader languages: DirectX (HLSL), OpenGL (GLSL), Metal (MSL), and others that FMX doesn't officially support, such as Vulkan (SPIR-V). Even within GLSL, there are some shader language variations that make the situation even more complicated.

Skia created SkSL (variation of GLSL), to standardize this. With it you can use a single shader code to render using the GPU in OpenGL, Metal, DirectX and Vulkan contexts, and even render in raster contexts (CPU) without use GPU.

Learn about the differences between SkSL and GLSL at this link https://github.com/google/skia/blob/main/src/sksl/README
