### ISSUE TITLE
Delphi 12: App will crash on Android if System.Skia is linked

### ISSUE THREAD

**Issue by atticoder** [skia4delphi/skia4delphi#280]
Hi,

Surprising issue out of the box. Can anyone use Skia on D12 and Android? App will crash while displaying splash screen as soon as System.Skia unit is used in project. Tried on 3 different devices from Android 6-13, no luck.

Created report at Quality Central:

https://quality.embarcadero.com/browse/RSP-43297

1) Create new blank multi-device application.
2) Add unit "System.Skia" to uses list of the main form.
3) Run the app on Android by the toolbar button "Run without debugging".

Alternatively just drop TSkSvg component on form, that will also put "System.Skia" into uses list.

The app will start and will display splash screen but hangs there. As soon "System.Skia" is removed from uses list, the app will start up just fine.

**Comment by viniciusfbb** [comment]
@atticoder Thank you for report the issue!

I guess that you forgot to enable skia in the project (Right click on the project > Enable Skia). This will automatically configure Skia binaries when deploying your app.

**Comment by viniciusfbb** [comment]
> I guess that you forgot to enable skia in the project (Right click on the project > Enable Skia). This will automatically configure Skia binaries when deploying your app.

This was the problem as replied by the user on jira. So, it is working as expected.
