### ISSUE TITLE
TSkPath.Contains() does not work properly in some situations

### ISSUE THREAD

**Issue by KaitoNakamura** [skia4delphi/skia4delphi#288]
We use Delphi 12 Enterprice on Windows 10 with the build in Skia4Delphi.

When using SkPath.TightBounds.Contains(), a False is returned in most situations. If you change the endpoint in CubicTo, SkPath.TightBounds.Contains() works reasonably well. The function cannot be used with straight lines. The value of "Stroke.StrokeWidth" appears to be independent of the calculation.

```
LPathBuilder := TSkPathBuilder.Create;
LPathBuilder.MoveTo(PointF(100.5,152));
LPathBuilder.CubicTo(PointF(0,0), PointF(0,0), PointF(150.5,152));
LPath := LPathBuilder.Detach;
SkiaCanvas.DrawPath(LPath, Stroke);
```

LPath.TightBounds.Contains Return **False** on this path.

or

```
LPathBuilder := TSkPathBuilder.Create;
LPathBuilder.MoveTo(PointF(100.5,152));
LPathBuilder.LineTo(PointF(150.5,152));
LPath := LPathBuilder.Detach;
SkiaCanvas.DrawPath(LPath, Stroke);
```

LPath.TightBounds.Contains Return **False** on this path.

Height or Width on TightBounds, depending on whether horizontal or vertical is 0.

**Comment by viniciusfbb** [comment]
@KaitoNakamura This is how the SkPath works on Google Skia. I recomend you to use the SkRegion to considere the stroke width. Take a look on this example: https://gist.github.com/viniciusfbb/df9c4d57102514faf105d2dddcd8d122

https://github.com/skia4delphi/skia4delphi/assets/11139086/88f262d0-c026-48e8-a655-63184ab055c2
