### ISSUE TITLE
Enabling Skia causes other controls to redraw abnormally

### ISSUE THREAD

**Issue by Leewx820** [skia4delphi/skia4delphi#289]
![image](https://github.com/skia4delphi/skia4delphi/assets/26474036/6826f8ad-9225-48c8-bb69-beb1b2215534)
![image](https://github.com/skia4delphi/skia4delphi/assets/26474036/e0773e38-0c70-441a-bfd6-17c48e1a6ced)

When the mouse moves to the second button, it triggers the Paint event of the first button, this only occurs if Skia is enabled, if Skia is disabled this does not occur, is this a feature of Skia or is there a problem?

**Comment by viniciusfbb** [comment]
@Leewx820 Thank you for your report!

This is expected. The TCanvasD2D (default render of FMX) is the only that currently implements the TCanvasStyle.SupportClipRects, that avoid full redraw of the form on each frame. If you add the `GlobalUseGPUCanvas := True;`, the render of the FMX will be the TCanvasGpu, that is, the DirectX, and will have the same problem without use Skia. All others platforms also behaves like Skia, drawing the full form on each frame. It is possible to implement the TCanvasStyle.SupportClipRects on Skia also, and could even improve the performance but is not so simple.

**Comment by Leewx820** [comment]
Okay, thank you for your work. Are there any plans to support this feature in the future?
