### ISSUE TITLE
TSkSVG not displaying SVG file properly

### ISSUE THREAD

**Issue by yesilcimenahmet** [skia4delphi/skia4delphi#292]
There is a browser view on the right side and TSkSVG on the left side. So are all versions of SVG fully supported? I would expect Skia to do a much more efficient job with SVG or is this the result of a missing implementation in Delphi? 

Note: same result with Runtime

![image](https://github.com/skia4delphi/skia4delphi/assets/20859682/d8f46cc5-94c3-41ed-94ad-89275bdc3d56)

Delphi Version: Delphi 12.0
Skika Version: Embedded Skia 6.0

Resources are below:

![outlook_live_stream_dark](https://github.com/skia4delphi/skia4delphi/assets/20859682/3dc3a6a4-7a25-4f74-9153-986847136367)
![com_jetbrains_intellij_code_search_polaris](https://github.com/skia4delphi/skia4delphi/assets/20859682/46d78a6a-af8a-4c07-8867-31d9c24a32f5)

**Comment by omonien** [comment]
I believe the PNG in that SVG is the root of the issues. Apparently, that PNG is used as a background tile, and scaling is not properly defined.

**Comment by viniciusfbb** [comment]
@yesilcimenahmet Skia's SVG implementation is reasonably good and fast, but it is not as complete as the library used by browsers, which include CSS processing, etc. So, although the main SVG sets are supported, there are still some SVG features not supported by Skia.
One tip is to use Figma to export some SVG, as Figma always tries to export in a format that has the greatest possible compatibility with SVG libraries, including Skia. So just paste it into Figma and copy as SVG again, and it will usually work.

**Comment by viniciusfbb** [comment]
Anyway, I'm closing this topic because I don't consider it a bug on Skia4Delphi's side. So, what we can do is document limitations/workaround (as we made [here](https://github.com/skia4delphi/skia4delphi/blob/main/Documents/SVG.md#limitations)) and [report Google Skia issues directly](https://issues.skia.org/issues) to them.
