### ISSUE TITLE
In Delphi 12 IDE crashes when you drag and drop TSkAnimatedPaintbox to Form

### ISSUE THREAD

**Issue by yesilcimenahmet** [skia4delphi/skia4delphi#293]
When you drag and drop the TSkAnimatedPaintbox component on the form, the IDE closes after a few seconds. You can see it in the video. But if you create the TSkAnimatedPaintBox instance in Runtime, you will not get an error.
Delphi 12 clean install and no external Skia version installed.

https://github.com/skia4delphi/skia4delphi/assets/20859682/ba9090b4-7cfe-40e8-afb5-266c991ce8fb

**Comment by viniciusfbb** [comment]
@yesilcimenahmet I can't reproduce it. It seems to me that the IDE is loading another sk4d.dll other than the one present in the $(BDS)\bin folder. Please make sure you do not have any other Skia4Delphi installation on the machine. Uninstall it and delete the directory if it exists. I will close now until we receive any new information from you.
