### ISSUE TITLE
ACCESS Violation after adding SKIA to Uses clause

### ISSUE THREAD

**Issue by ZaakaJarimbo** [skia4delphi/skia4delphi#294]
I have just reinstalled SKIA on my Win11, DELPHI 11.3, SKIA 6.0.0 system and added `System.Skia, Vcl.Skia` to my uses clause and i am now getting an ACCESS VIOLATION error when running the app.

is this a known issue? has anybody else had this?

![Skia_error](https://github.com/skia4delphi/skia4delphi/assets/5955746/30b5f19c-72a1-498b-896f-175dd221d601)

**Comment by ZaakaJarimbo** [comment]
Here is the error
![Skia_error0](https://github.com/skia4delphi/skia4delphi/assets/5955746/93eab287-ef97-438a-8611-85db490742ea)

**Comment by ZaakaJarimbo** [comment]
Sorry Guys, i noticed I am running Windows 64 config, switched to Windows 32 and is now working :(

**Comment by viniciusfbb** [comment]
No problem!
