### ISSUE TITLE
Android Crash on Delphi 11.3 for Transferred Bricks Game Demo Project

### ISSUE THREAD

**Issue by MrYoksul** [skia4delphi/skia4delphi#297]
Issue Description:
I am experiencing an issue with a Bricks Game Demo project in Delphi 11.3. The project runs successfully on Win32, but it crashes immediately on Android.

Steps Taken:

Created a new project in Delphi 11.3.
Transferred all files and settings from the original demo project to the new project.
Verified that the demo project runs on both Win32 without issues.
Current Behavior:

On Win32, the newly created project runs without any problems.
On Android, the application crashes immediately upon launch.
Expected Behavior:
The application should run on Android as smoothly as it does on Win32.

Troubleshooting Attempted:
Checked for any differences between the original demo and the new project. The only noticeable difference is the project name.

Request:
Could you assist in identifying and resolving the issue causing the Android crash in the new project?

**Comment by viniciusfbb** [comment]
@MrYoksul Did you enabled the Skia on your new project? (Right click on project > Enable Skia)
Also, did you check the deployment files of old project vs new project?

**Comment by viniciusfbb** [comment]
Closed due to lack of information. Please feel free to post more information here, and then I can reopen the discussion.
