### ISSUE TITLE
Error compiling for Delphi 10.4 Sydney - Skia.Package.RTL.dproj - Win32

### ISSUE THREAD

**Issue by ViniciusAguiar23** [skia4delphi/skia4delphi#30]
I have been trying to install the latest version of Skia4Delphi, but in both recommended ways to install it (GetIt or Setup), a message error keeps appearing. I'm attaching the message here (it asked to report this issue). How should I proceed?
![skia4delphi](https://user-images.githubusercontent.com/57021328/149555068-68271533-c093-48bc-8a60-e44b3df999fc.png)

**Comment by viniciusfbb** [comment]
Hi @ViniciusAguiar23! Thank you very much to report the issue.

1) Could you send us the Build.Logs.txt file? This file generated in the installation folder when an error occurs).
2) What edition is your RAD Studio? (Community, Trial, Started...)

**Comment by viniciusfbb** [comment]
I need to confirm through Build.Logs.txt, but I'll tell you that it's probably the same problem as issue [7 - Error to install the component in Delphi 10.4.2](#7). This problem is especially common with Brazilians because ACBr takes up a lot of space in the IDE's Library Path. I indicated a workaround for his problem, but this specific problem has been resolved and will be available in the next release later this month.

**Comment by ViniciusAguiar23** [comment]
> 

I was unable to locate the file you asked, I tried looking the folder where it was installed, but i couldn't find it. My RAD Studio is neither Community nor Trial, it's a paid license version. Should I try the workaround you suggested?

**Comment by viniciusfbb** [comment]
Do you have ACBr installed? If so, then it's definitely the same problem and you can try the workaround.
About the Build.Logs.txt, in addition to it being saved in the installation folder, clicking Ok on the error message will open our issues page and the notepad with the contents of Build.Logs.txt.

**Comment by ViniciusAguiar23** [comment]
> Do you have ACBr installed? If so, then it's definitely the same problem and you can try the workaround. About the Build.Logs.txt, in addition to it being saved in the installation folder, clicking Ok on the error message will open our issues page and the notepad with the contents of Build.Logs.txt.

I don't have ACBr installed. When I clicked Ok on the error message, it opened the issue page, but it didn't open the notepad. I'm sending you the folder where Skia4Delphi was installed, so maybe you can help me find the file
![skia4delphi2](https://user-images.githubusercontent.com/57021328/149565027-2eb7106a-f483-46c1-b042-068fae517742.png)

**Comment by viniciusfbb** [comment]
I just discovered a problem: installing via GetIt is not generating the Build.Logs.txt (I will fix this in the next release as well).
Do the following:

1) Open RAD Studio and uninstall via GetIt.
2) Close RAD Studio and install Skia4Delphi using our setup: [Skia4Delphi_2.0.1_Setup.exe](https://github.com/viniciusfbb/skia4delphi/releases/download/v2.0.1/Skia4Delphi_2.0.1_Setup.exe)

Any questions can send me on WhatsApp +55 38 98816-9152 or Telegram [@viniciusfbb](https://t.me/viniciusfbb)

**Comment by viniciusfbb** [comment]
Issue accepted. In fact there are some problems with the current installer. The entire installation process needs to be improved and/or redone.

**Comment by viniciusfbb** [comment]
The problem was solved in new release. Please download new version 3.0.0.
