### ISSUE TITLE
error: program is too large

### ISSUE THREAD

**Issue by yimmasabi** [skia4delphi/skia4delphi#307]
I receive this error when I have i,j loop to analyze bitmap pixels of a shader texture. Normally it is about 5000x5000 pixels, and I get error in the mid of loop. Then I found that there is a limit about loops, depends on lines inside. When I test this simplified example below on https://shaders.skia.org/, you have

`error: program is too large`

Here if you set loop to 12498, or less numbers, you have no error.

`vec4 main( in vec2 fragCoords )
{
   vec3 c = vec3(0.2,0.7,0.5);
   
   for(int i=0; i<12500; i++)
   { 
     vec4 pa = vec4(0,0,0,0 );
   }

   return( vec4(c , 1) );
}`

I found discussion here;
https://groups.google.com/g/skia-discuss/c/RiMdRhnFL0Y/m/oeE21-xcAgAJ

I know, analyzing bitmap is confusing for a single shader but I am using it as a data input. 
How can we do larger loops as in this example above? Is it possible ?

**Comment by viniciusfbb** [comment]
@yimmasabi Unfortunately it is a limitation of SKSL to be compatible with the maximum numbers of GPUs as possible, especially mobile. The steps of each call cannot be so big (after expanding the loops). :(
Maybe if you explain the context better, the real objective of your shader, we can think of a different approach (but this is not always possible).

**Comment by viniciusfbb** [comment]
Unfortunately it is a limitation of Google Skia as mentioned previously.
