### ISSUE TITLE
TSkSvg with an SVG with french special caracters

### ISSUE THREAD

**Issue by NizarUPC** [skia4delphi/skia4delphi#308]
Hello I have an issue with TskSvg when I try to display an SVG that containing french caracters like 'é'. 

Is there something that I do not understand or a real bug ?

Thank you in advance.

**Comment by viniciusfbb** [comment]
The problem is because you are saving the file using ANSI instead UTF-8. There are some ways to detect ANSI or UTF-8 but it is not 100% certain. For now, we have added a small improvement to support UTF-16 and UTF-32 as well, and in the future maybe we can provide a better solution to this issue.

**Comment by NizarUPC** [comment]
My svg file is UTF-8.

When I import the file programmatically, it doesn't work but if works fine when I import it from the SVG editor in the DFM

**Comment by viniciusfbb** [comment]
@NizarUPC In this case, it has no relation to Skia4Delphi library as SVG does not directly load the file. You are the one who has to load the file and feed SkSVG only with the source string. So for your code there are 2 solutions:
1. Save the file as UTF-8 with BOM;
2. Upload the file explicitly stating that it is UTF-8:
```pascal
uses
  System.IOUtils;

procedure TForm1.FormCreate(Sender: TObject);
begin
  SkSVG1.Svg.Source := TFile.ReadAllText('C:\Users\vinic\Desktop\a.svg', TEncoding.UTF8);
end;
```

The cause of this is that TFile.ReadAllText (as well as other Delphi functions) considers that the text is encoded as ANSI when it does not find any BOM.

**Comment by NizarUPC** [comment]
Thank you !
