### ISSUE TITLE
Make more classes public in vcl.skia

### ISSUE THREAD

**Issue by cmbant** [skia4delphi/skia4delphi#316]
At the moment it seems you can't test if a graphic is TSkGraphic because that class is private. Also, since the unit registers SVG, which may conflict e.g. with TMS Software or SVGIconImage which also register SVG, you also can't get at TSkSvgGraphic to unregister it because that is also private.

**Comment by viniciusfbb** [comment]
@cmbant Thanks for report the issue. I'm closing it now as there is another one with the same subject.

Duplication of #271
