### ISSUE TITLE
Problema desconhecido com Delphi 12.1 e Skia4Delphi no Android64

### ISSUE THREAD

**Issue by mariodelfino97** [skia4delphi/skia4delphi#319]
Olá Vinicius e Paulo,

Primeiramente, parabéns pelo projeto Skia4Delphi!!

Iniciei testes com o Skia4Delphi num projeto que estou desenvolvendo e decidi usar em especial TSkAnimatedImage para carregar alguns Loadings que achei maravilhosos.

Eu já estou trabalhando com o Delphi 12 Athenas com Update 1.

Info Android:
Aparelho Galaxy A54
One UI 6.1
Android 14

Mesmo com o Delphi 12 que já vem com o Skia4Delphi baixei e instalei a versão mais recente do Skia. 
Segui as orientações descritas na documentação tais como [Enable Skia] no Project Inspector, além das linhas abaixo.

  GlobalUseMetal := True;
  GlobalUseVulkan := True;
  GlobalUseSkiaRasterWhenAvailable := False;
  GlobalUseSkia := True;
  
No iOS compilou, executou e funcionou perfeitamente.
No entanto, no Android compilou sem erros, a aplicação abre mas ao realizar operações simples como uma transição de um tabControl (exemplo abaixo), a aplicação fecha instantaneamente. 

tab00.GotoVisibleTab(1, TTabTransition.Slide, TTabTransitionDirection.Normal);

Preocupado em ter o App funcionando, tentei [Disable Skia] no Project Inspector, compilou e instalou, mas a aplicação não abre.
Por fim, removi todas declarações relacionadas ao Skia e só assim o App voltou a funcionar no Android.

Fiquei muito chateado, porque gostei muito de usar o componente TSkAnimatedImage, já que de forma tão simples, apenas carregando um arquivo JSON (Lotties), é possível usar uma animação tão profissional.

Se puderem dar alguma dica sobre fazê-lo funcionar no meu ambiente coloco aqui meu contato:
mariodelfino97@gmail.com

Obrigado e mais uma vez parabéns!
Mario Delfino

**Comment by viniciusfbb** [comment]
@mariodelfino97 O RAD Studio 12.1 ja vem com a ultima versao do Skia4Delphi, entao eu te aconselho usar apenas a versao do RAD Studio. Siga os passos:
1. Desinstale o Skia4Delphi que vc instalou por conta propria, geralmente fica em `C:\Users\<user>\Documents\Skia4Delphi\`. Basta rodar o `unins000.exe` ou ir no painel de controle remover aplicacao > Skia4Delphi.
2. Com o RAD Studio fechado, dele toda a pasta de output do seu projeto para garantir que a IDE nao use nenhuma dcu antiga da lib.
3. Rode e veja se funcionou;

Caso nao funcione, compile em modo debug e mande o callstack. Quando a aplicacao fecha, eh pq houve um exception, entao vc conseguira capturar detalhes deste exception debugando, e compartilhar conosco.

**Comment by viniciusfbb** [comment]
Alem disso, um projeto mínimo reproduzindo o issue ajudaria muito também.

**Comment by mariodelfino97** [comment]
Olá Vinicius,

Obrigado pelo retorno.
Vou seguir suas orientações.

**Comment by viniciusfbb** [comment]
@mariodelfino97 Voce tem mais alguma informação sobre esse issue? Ja foi resolvido?

**Comment by viniciusfbb** [comment]
@mariodelfino97 This issue will have to be closed due to lack of feedback from the reporter. Feel free to open a new issue or add comments to this issue so we can validate and reopen the topic.
