### ISSUE TITLE
Access Violations with combinations of Skia Options

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [skia4delphi/skia4delphi#328]
First thing, the code: 

    var LCanvas := TSkCanvasCustom(Bitmap.Canvas).Canvas

Returns NIL if GlobalUseSkia is not set to TRUE

When GlobalUseSkia IS Set to True and  GlobalUseSkiaRasterWhenAvailable = false

then a form with Skia Controls shows up as a white frame for a moment (most noticeable in Debugger) before actually correctly displaying

and if GlobalUseGPUCanvas = true then I get an access violation.  These are all under Win32

Here is the sample project:

https://github.com/user-attachments/assets/736423b6-cfa9-45d0-b6
[Skia Issue.zip](https://github.com/user-attachments/files/16327320/Skia.Issue.zip)
78-cb50f1ba25c8

Here is a video demonstrating what I'm talking about.

https://github.com/user-attachments/assets/fbaf71d6-e553-4d84-8ac8-3078420a3573

Finally, I did some timings, and turning on GlobalUseSkia seems to slow things down more than it speeds it up...

![image](https://github.com/user-attachments/assets/d512a527-46d1-4f10-a73f-429eeab95147)

**Comment by viniciusfbb** [comment]
@TheOriginalBytePlayer you should check if Bitmap.Canvas is a TSkCanvasCustom class first, because when GlobalUseSkia is False, you shouldn't do this cast as the canvas will be one of the FMX default implementation.

About speed, bitmaps draws using skia are slightly slower because we are using CPU (raster) always, and GPU only for the form canvas. This approach was chosen because this allow us to use TBitmap draws in a real parallel way, that is, without lock the UI/others bitmaps as it is now on the default FMX canvas implementation. SkiaSharp does the same.

So, for performance, although bitmaps draws using skia are slightly slower, the app render in general is faster.

**Comment by TheOriginalBytePlayer** [comment]
> you should check if Bitmap.Canvas is a TSkCanvasCustom class first, because when GlobalUseSkia is False, you shouldn't do this cast as the canvas will be one of the FMX default implementation.

Might I respectfully ask that this is put into the documentation, and/or optionally have it return an exception rather than nil so make it easier to catch this issue.

> About speed, bitmaps draws using skia are slightly slower because we are using CPU (raster) always, and GPU only for the form canvas

Does this mean that if I'm just rendering a bitmap then skPaintBox will always be slower than tPaintBox?

**Comment by TheOriginalBytePlayer** [comment]
Thank you for your quick response on the rendering speed issues but you did not address the access violation and white screen artifacts I described.

### WHITE FRAME ARTIFACT

When **GlobalUseSkia IS Set to True** and **GlobalUseSkiaRasterWhenAvailable = false**

then a form with Skia Controls shows up as a white frame for a moment (most noticeable in Debugger) before actually correctly displaying (SEE VIDEO  IN ORIGINAL MESSAGE)


### ACCESS VIOLATION WHEN GlobalUseGPUCanvas = true

Pretty much self-explanatory

Here is the sample project:

https://github.com/user-attachments/assets/736423b6-cfa9-45d0-b6
[Skia Issue.zip](https://github.com/user-attachments/files/16327320/Skia.Issue.zip)
78-cb50f1ba25c8

**Comment by viniciusfbb** [comment]
@TheOriginalBytePlayer Your link seems broken.

**Comment by TheOriginalBytePlayer** [comment]
Yeah, don't know what that other link was.  Here it is (and I've tested it even!)

[Source Code for this Skia Issue.zip](https://github.com/user-attachments/files/16327320/Skia.Issue.zip)

**Comment by viniciusfbb** [comment]
@TheOriginalBytePlayer Sorry for the delay, but today I was able to see the demo and I noticed one mistake in your code. Take a look on this code:
```pascal
    var AlphaTester:=TBitmap.Create(Round(Width),Round(Height));
    AlphaTester.SkiaDraw(
      procedure (const LCanvas: ISkCanvas)
      begin
        if assigned(LCanvas) then
           Label1.Text:='Bitmap.SkiaDraw(proc()) WORKS'
        else
           Label1.Text:='Bitmap.SkiaDraw(proc()) FAILS';
      end);
    AlphaTester.Canvas.BeginScene();
    var LCanvas := TSkCanvasCustom(AlphaTester.Canvas).Canvas;
    if assigned(LCanvas) then
       Label2.Text:='TSkCanvasCustom(AlphaTester.Canvas).Canvas WORKS'
    else
       Label2.Text:='TSkCanvasCustom(AlphaTester.Canvas).Canvas) FAILS';
    AlphaTester.Canvas.EndScene;
    AlphaTester.Free
```
`Bitmap.SkiaDraw` will work always, but the cast `TSkCanvasCustom(Bitmap.Canvas)` not and this is expected. The `GlobalUseSkia` or `GlobalUseMetal` or `GlobalUseGPU` or `GlobalUseVulkan`, etc, they always register a canvas class to be internally used by the FMX on Form (and Controls) and on Bitmaps.

The `GlobalUseSkia` means the render of your entire app will be Skia based. If you use `GlobalUseSkia := True;` all TCanvas of your app will be descendent of `TSkCanvasCustom`, so you can cast it always, like `TSkCanvasCustom(Bitmap.Canvas)`. If `GlobalUseSkia := False;` all TCanvas of your app won't be descendent of `TSkCanvasCustom` (they might be descendent of (TCanvasGPU, TD2DCanvas or any other FMX internal implementation that doesn't use Skia), so you can't cast it to `TSkCanvasCustom`.

The right way to check is simply by add a `if Canvas is `TSkCanvasCustom then`, but this should be useful only for paint events of controls. For bitmap draws, we always recommend use` Bitmap.SkiaDraw`, that works always, regardless the `GlobalUseSkia` value, regardless the framework (VCL or FMX).

**Comment by viniciusfbb** [comment]
@TheOriginalBytePlayer If the problem was clarified with my previous post, can I close the issue? Let me know if you have any further questions.

**Comment by viniciusfbb** [comment]
@TheOriginalBytePlayer This issue will have to be closed due to lack of feedback from the reporter. Feel free to open a new issue or add comments to this issue so we can validate and reopen the topic.
