### ISSUE TITLE
Erro Code ( 6 ) 

### ISSUE THREAD

**Issue by Marcalinfo** [skia4delphi/skia4delphi#335]
Ao realizar uma instalação no Delphi 10.3 ocorre o seguinte erro : Falha ao instalar o package "Skia.Package.VCL.dproj" no RAD Studio 10.3 Rio - Win64 (código 6)

Alguém passou por isso e pode me ajudar ?

**Comment by viniciusfbb** [comment]
@Marcalinfo Can you provide more information about your issue? I tested the v6.2.0 on Delphi 10.3 Rio and it ir working for me.

Note: The installer of RAD Studio 10.3 Rio allow you to install only Win32 (without Win64). And our setup and plugin always assume that there are both Win32 and Win64 platforms in your RAD Studio. If this is the issue, I advise you to install the Win64 platform.

**Comment by viniciusfbb** [comment]
@Marcalinfo I'm closing due the lack of feedback. Please, feel free to add more details here to allow us reopen the issue or even creating a new issue.
