### ISSUE TITLE
skiaDraw draw an empty image

### ISSUE THREAD

**Issue by Lingri** [skia4delphi/skia4delphi#369]
Hello! I have a question about using function SkiaDraw with pathBuilder.
My code is like that:

```
var skiaBMP: TBitmap;
skiaBMP.SetSize(400, 200);

skiaBMP.SkiaDraw(
    procedure(const ACanvas: ISkCanvas)
    var paint: ISkPaint;
        path : ISkPathBuilder;
        rect: TRectF;
        polygon: TPolygon;
    begin
      paint := TSkPaint.Create;
      path := TSkPathBuilder.Create;
      paint.Color := clGreen;

      path.AddRect(TRectF.Create(0, 0, 100,100));
      ACanvas.DrawPath(path.Detach, paint);
end);

skiaBMP.SaveToFile('E:\skia.bmp');
```

In my opinion, i want to see green rect in my image, but it's empty. 
I need ISkPathBuilder to draw more difficult example, with polygons and different colors/styles, but cant get result in simple example.
Can you help me, what am I doing wrong?

**Comment by viniciusfbb** [comment]
@Lingri The problem in your code is the line `paint.Color := clGreen;` that should be `paint.Color := TAlphaColors.Green;`. The entire api of Skia works only with TAlphaColor, but you can convert easily from TColor...
