### ISSUE TITLE
Installation Fails on Delphi 11 Professional

### ISSUE THREAD

**Issue by Mr-KultiVator** [skia4delphi/skia4delphi#37]
Using the Skia4Delphi Setup.exe installation method, the setup wizard halts with the following error...

![image](https://user-images.githubusercontent.com/99536360/153708664-4135db80-02f5-469a-8630-2049e9ff4f48.png)

As I have Delphi 11 Professional, my machine has no FMX Linux capabilities :-(  so it looks like the installation program assumes Delphi Exterprise / Architect Edition is installed.

The same error occurs on several Delphi 11 installs - in VMs and on a physical machine.

**Comment by viniciusfbb** [comment]
@Mr-KultiVator Thank you very much to report the problem!

I fixed the problem and updated [Skia4Delphi_3.0.0_Setup.exe](https://github.com/skia4delphi/skia4delphi/releases/download/v3.0.0/Skia4Delphi_3.0.0_Setup.exe)
Can you download and test again?

**Comment by Mr-KultiVator** [comment]
> 

Now that's what I call a quick fix!

Everything working great in both FMX and VCL.

Amazing work - huge thanks for creating this impressive library and sharing this with the Delphi Community.
