### ISSUE TITLE
Error message with TSkLabel on VCL form

### ISSUE THREAD

**Issue by sw-berrag** [skia4delphi/skia4delphi#41]
![error](https://user-images.githubusercontent.com/34064530/153819448-e1aac8b5-463c-4eb5-904c-1e4d9e9c46d0.png)

**Comment by sw-berrag** [comment]
1. Yes, in the Designtime.
2. When try to Edit TextSettings in the object inspector ( TSkLabel)
3. Always.
4. Embarcadero RAD Studio 11.0 Version 28.0.42600.6491 
[https://i.ibb.co/ZHzm5Wr/Skia.gif](url)

**Comment by viniciusfbb** [comment]
1) Did you install manually or using Setup?
2) Have you tried to reinstall?
3) Did you edit something in the form before the problem started?
4) When using TSkLabel in a blank project, does the error occur?

I need more information, so far I haven't been able to reproduce the problem, I've tested it on multiple Windows 10 or 11 computers, from XE7 to Alexandria.

**Comment by sw-berrag** [comment]
The problem is fixed by reinstalling by Setup file and delete all old versions.
Thanks for this great changes.
