### ISSUE TITLE
Error parsing SVG files without DOCTYPE ENTITY content 

### ISSUE THREAD

**Issue by carloBarazzetta** [skia4delphi/skia4delphi#43]
[playing-cards.zip](https://github.com/skia4delphi/skia4delphi/files/8063485/playing-cards.zip)
[flags.zip](https://github.com/skia4delphi/skia4delphi/files/8063486/flags.zip)
Hi guys, I've attached another series of SVG images with rendering problems...
Thank you.
Carlo

**Comment by viniciusfbb** [comment]
@carloBarazzetta First of all, thank you so much again for reporting an issue! This makes the library even better.

Regarding the case, this is another limitation of Skia. It does not yet support inner `<symbol>` elements. We believe that in a short time these limitations will disappear, as Flutter also from Google uses the same module for rendering SVGs. In any case, it is an extremely fast and stable parser, despite the limitations. In fact, in a benchmark we did, it was faster than Image32, D2D and Cairo.

I apologize in advance for not documenting it sooner. We tested it with thousands of app icon svgs (using top SVG icon sets, like, Bootstrap Icons, Font Awesome Icons, Material Design Icons by Google, Octicons by Github) and all rendered perfectly.

**Comment by carloBarazzetta** [comment]
Thanks @viniciusfbb, I also did some performance tests and SKIA is very fast, I can't wait to be able to use it with my components and with most of the SVG files available!

**Comment by carloBarazzetta** [comment]
Sorry for my error regarding SVG's contained into flags.zip: those files works perfectly with SKIA4Delphi, I've made an error implementing support for SVGIconImageList, now fixed.

**Comment by viniciusfbb** [comment]
Nice!
