### ISSUE TITLE
Dont Work after compile in Windows 11, but in Android works... | Não funciona após compilar para o Windows 11, mas nos Android funciona.

### ISSUE THREAD

**Issue by jeferssonjeiel** [skia4delphi/skia4delphi#46]
**[en]**
I installed Skia4Delphi following the documentation, including using the latest version, and after some tests it worked without problems, however after a while of use it didn't work anymore.

The "SKLABEL" Component displays the text at design time, but after compiling (on windows 11) the text doesn't show anything. However if you do the same process on android, it works without problems.

I do not know what to do. I don't know if I'm doing something wrong, or it's something on my computer that is suddenly missing some windows libraries.

**[pt]**
Eu instalei o Skia4Delphi seguindo a documentação, inclusive usando a última versão, e após alguns testes funcionou sem problemas, entretanto depois de um tempo de uso não funcionou mais.

O Componente "SKLABEL" exibe o texto em tempo de design, mas após compilar (no windows 11) o texto não mostra nada. Entretanto se fizer o mesmo processo no android, funciona sem problemas.

Não sei o que fazer. Não sei se eu estou fazendo algo errado, ou é algo no meu computador que falta, de repente algumas bibliotecas do windows.

**Problem | Problema:**

![Recording 2022-02-15 at 15 32 18](https://user-images.githubusercontent.com/47994766/154126556-6511b83f-d9a0-468b-8b31-d914cbd549b0.gif)

**Comment by viniciusfbb** [comment]
Você tinha alguma versão antiga do Skia4Delphi?

**Comment by jeferssonjeiel** [comment]
> Olá @jeferssonjeiel, muito obrigado por reportar o problema!
> 
> A instalação foi feita manualmente ou utilizando o instalador?

Olá amigo, muito obrigado por responder!

**Eu utilizei o próprio instalador que é recomendado na documentação.** Eu tentei de modo manual mas não cheguei até o final, achei um pouco complicado, hehe...

**Comment by jeferssonjeiel** [comment]
> Você tinha alguma versão antiga do Skia4Delphi?

**Não tinha nenhum versão anterior.** Pois eu tinha o conhecimento dessa biblioteca a poucos dias, então assim que tive o conhecimento eu fui instalar.

**Comment by viniciusfbb** [comment]
Você clicou com o botao direito no projeto > Enable Skia?

**Comment by jeferssonjeiel** [comment]
> Você clicou com o botao direito no projeto > Enable Skia?

**Sim, cliquei sim.** (Detalhe: É Normal que quando você habilite da primeira vez ele sempre ficará ativo para o projeto completo?) (No momento eu desinstalei o Skia, vou instalar novamente para caso eu tinha deixado passar alguma coisa). Tudo que estou relatando aqui, posteriormente eu vou fazer um vídeo explicando o projeto e dando dicas de algumas dificuldades que eu tive para que outros não tenham.

**Comment by viniciusfbb** [comment]
> > Olá @jeferssonjeiel, muito obrigado por reportar o problema!
> > A instalação foi feita manualmente ou utilizando o instalador?
> 
> Olá amigo, muito obrigado por responder!
> 
> **Eu utilizei o próprio instalador que é recomendado na documentação.** Eu tentei de modo manual mas não cheguei até o final, achei um pouco complicado, hehe...

Sim. Você tentou fazer a instalação manual antes ou depois da instalação pelo instalador?

**Comment by jeferssonjeiel** [comment]
> > > Olá @jeferssonjeiel, muito obrigado por reportar o problema!
> > > A instalação foi feita manualmente ou utilizando o instalador?
> > 
> > 
> > Olá amigo, muito obrigado por responder!
> > **Eu utilizei o próprio instalador que é recomendado na documentação.** Eu tentei de modo manual mas não cheguei até o final, achei um pouco complicado, hehe...
> 
> Sim. Você tentou fazer a instalação manual antes ou depois da instalação pelo instalador?

**Eu tentei fazer a instalação manual depois que fiz a instalação "automática".** O Motivo é que, como não estava funcionando com a automática eu pensei..., "ahh, então eu vou tentar a manual", mas não consegui.

**Comment by jeferssonjeiel** [comment]
Foi assim que eu fiz a instalação do Skia4Delphi

![Recording 2022-02-16 at 08 09 10](https://user-images.githubusercontent.com/47994766/154252677-cfc0f47d-5205-4a91-8847-6c04962fbb87.gif)

**Comment by viniciusfbb** [comment]
Ok. Quero que faça um teste pra mim:

1) Desinstale o Skia4Delphi (pelo settings do Windows ou pelo unins000.exe na pasta da instalação)
2) Apague a pasta do Skia4Delphi que vc usou na instalação manual
3) Instale pelo instalador
4) Na pasta da instalação, abra o projeto Packages\RAD Studio 10.4 Sydney\Skia4Delphi.groupproj 
5) Clique em Show Build Groups Panel (É um ícone que fica no painel dos projetos na IDE);
6) No painel do Build Groups que abrir, selecione apenas Win32 e Win64 (exceto nos packages com final .DesignTime no nome que não terão a opção do Win64)
7) Ainda no projeto Build Groups, clica em Build All (É um ícone também)
8) Reabra a IDE e teste se o erro continuará;

**Comment by jeferssonjeiel** [comment]
> Ok. Quero que faça um teste pra mim:
> 
> 1. Desinstale o Skia4Delphi (pelo settings do Windows ou pelo unins000.exe na pasta da instalação)
> 2. Apague a pasta do Skia4Delphi que vc usou na instalação manual
> 3. Instale pelo instalador
> 4. Na pasta da instalação, abra o projeto Packages\RAD Studio 10.4 Sydney\Skia4Delphi.groupproj
> 5. Clique em Show Build Groups Panel (É um ícone que fica no painel dos projetos na IDE);
> 6. No painel do Build Groups que abrir, selecione apenas Win32 e Win64 (exceto nos packages com final .DesignTime no nome que não terão a opção do Win64)
> 7. Ainda no projeto Build Groups, clica em Build All (É um ícone também)
> 8. Reabra a IDE e teste se o erro continuará;

1. Desinstalado pelo unins000.exe na pasta de instalação.
2. Assim que eu desinstalei a pasta foi deletada.

![Recording 2022-02-16 at 08 26 18](https://user-images.githubusercontent.com/47994766/154255433-fc7e70ca-8e39-4c65-86fb-e7666069bfc7.gif)

3. Instalei pelo Instalador
4. Abri o projeto demo na pasta "Packages\RAD Studio 10.4 Sydney\Skia4Delphi.groupproj"

![16-02-2022-1](https://user-images.githubusercontent.com/47994766/154257616-ce19b959-e1a0-4b85-bf95-bf8d072fee99.gif)

5. Eu encontrei o menu **Show Build Groups Panel** mas **não há nenhuma versão de Build Group para ser selecionado**, entretanto é possível criar novos.

![16-02-2022-2](https://user-images.githubusercontent.com/47994766/154259789-04421fe4-dff8-4a4b-8e2d-395ab71ebc1f.gif)

6. Não sei se vai adiantar muito dar um Build já que a faltou por alguma razão realizar de forma correta a opção anterior, pois faltou provavelmente algumas opções, entretanto eu dei um Build, re-abri a IDE e verifiquei se o erro continua.

![16-02-2022-3](https://user-images.githubusercontent.com/47994766/154260865-8240e35d-7ec1-47e5-8a35-43e53d485be2.gif)

---

Espero ter feito tudo correto. Por favor pode pedir o que quiser de testes para eu fazer por aqui, se isso for para contribuir com o projeto de algum modo, estou aqui para ajudar sempre que puder.

**Comment by viniciusfbb** [comment]
> Abri o projeto demo na pasta "Packages\RAD Studio 10.4 Sydney\Skia4Delphi.groupproj"
Passo 4 não está correto. Você abriu o Demo ao invés de abrir o group project da pasta "Skia4Delphi\Packages\RAD Studio 10.4 Sydney\Skia4Delphi.groupproj"

**Comment by jeferssonjeiel** [comment]
Realmente foi falta de atenção minha..., eu tentei da forma que você falou e acho que pode não ter funcionado. Veja só (Gif longo):
![16-02-2022-4](https://user-images.githubusercontent.com/47994766/154264666-cc467a00-ea34-4bb8-9d23-8eab96412342.gif)

Por favor, se eu fiz algo errado, pode me falar.

**Comment by viniciusfbb** [comment]
Jeferson, tem como eu acessar sua máquina? Me adiciona no telegram: [viniciusfbb](https://t.me/viniciusfbb)

**Comment by jeferssonjeiel** [comment]
> Jefersson, tem como eu acessar sua máquina? Me adiciona no telegram: [viniciusfbb](https://t.me/viniciusfbb)

Bom..., no momento eu estou fazendo um projeto aqui, não é possível, mas podemos combinar. Digo..., para hoje só se for para mais tarde, tipo, 22hrs (kkkk), mas posso te falar que o dia que eu fico disponível para cedo é na sexta feira. A partir das 18hrs eu já estou disponivel.

Vou te adicionar no telegram, a gente pode conversar por lá.

**Comment by viniciusfbb** [comment]
Ok

**Comment by viniciusfbb** [comment]
The problem has been resolved. As the Demo was running in a virtual machine, with limited OpenGL support, only raster mode is working.
