### ISSUE TITLE
AV in Metal with effects

### ISSUE THREAD

**Issue by FMXExpress** [skia4delphi/skia4delphi#57]
I'm using this on iOS 15.2:

  GlobalUseMetal := True;
  GlobalUseSkia := True;
  GlobalEventDrivenDisplayUpdates := False;

And I get a crash in animation or maybe effects. Here is the call stack:

Fmx.Context.Metal.TContextMetal.DoCopyToBits(void const*, int, System.Types.TRect const&)(??,0x0000000112b74000,0x000000016b2450b0)
Fmx.Types3d.TContext3D.DoCopyToBitmap(Fmx.Graphics.TBitmap*, System.Types.TRect const&)(0x000000010b498ad0,0x0000000280a8b2f0,0x000000016b2450b0)
Fmx.Context.Metal.TContextMetal.DoCopyToBitmap(Fmx.Graphics.TBitmap*, System.Types.TRect const&)(0x000000010b498ad0,0x0000000280a8b2f0,0x000000016b2450b0)
Fmx.Types3d.TContext3D.CopyToBitmap(Fmx.Graphics.TBitmap*, System.Types.TRect const&)(0x000000010b498ad0,0x0000000280a8b2f0,0x000000016b2450b0)
Fmx.Effects.TFilterEffect.ProcessEffect(Fmx.Graphics.TCanvas*, Fmx.Graphics.TBitmap*, float)(0x000000010b33bfd0,0x0000000280a8b2f0)
Fmx.Controls.TControl.ApplyEffect()(0x000000010b90fe00)
Fmx.Controls.TControl.PaintInternal()(??)
Fmx.Controls.TControl.PaintChildren()(0x000000010b94b800)
Fmx.Controls.TControl.PaintInternal().DoPaintInternal(void*)(0x000000016b245a78)
Fmx.Controls.TControl.PaintInternal().PaintAndClipChild(void*)(0x000000016b245a78)
Fmx.Controls.TControl.PaintInternal()(??)
Fmx.Controls.TControl.PaintChildren()(0x000000010babcc00)
Fmx.Controls.TControl.PaintInternal().DoPaintInternal(void*)(0x000000016b245f08)
Fmx.Controls.TControl.PaintInternal().PaintAndClipChild(void*)(0x000000016b245f08)
Fmx.Controls.TControl.PaintInternal()(??)
Fmx.Controls.TControl.PaintChildren()(0x000000010c46ce00)
Fmx.Controls.TControl.PaintInternal().DoPaintInternal(void*)(0x000000016b246398)
Fmx.Controls.TControl.PaintInternal().PaintAndClipChild(void*)(0x000000016b246398)
Fmx.Controls.TControl.PaintInternal()(??)
Fmx.Controls.TControl.PaintChildren()(0x000000010c074800)
Fmx.Controls.TControl.PaintInternal().DoPaintInternal(void*)(0x000000016b246828)
Fmx.Controls.TControl.PaintInternal().PaintAndClipChild(void*)(0x000000016b246828)
Fmx.Controls.TControl.PaintInternal()(??)
Fmx.Controls.TControl.PaintChildren()(0x000000010c1c7a00)
Fmx.Controls.TControl.PaintInternal().DoPaintInternal(void*)(0x000000016b246cb8)
Fmx.Controls.TControl.PaintInternal().PaintAndClipChild(void*)(0x000000016b246cb8)
Fmx.Controls.TControl.PaintInternal()(??)
Fmx.Controls.TControl.PaintChildren()(0x000000010c05f000)
Fmx.Controls.TControl.PaintInternal().DoPaintInternal(void*)(0x000000016b247148)
Fmx.Controls.TControl.PaintInternal().PaintAndClipChild(void*)(0x000000016b247148)
Fmx.Controls.TControl.PaintInternal()(??)
Fmx.Controls.TControl.PaintChildren()(0x000000010c071c00)
Fmx.Tabcontrol.TTabItem.PaintChildren()(0x000000010c071c00)
Fmx.Controls.TControl.PaintInternal().DoPaintInternal(void*)(0x000000016b2475f8)
Fmx.Controls.TControl.PaintInternal().PaintAndClipChild(void*)(0x000000016b2475f8)
Fmx.Controls.TControl.PaintInternal()(??)
Fmx.Tabcontrol.TTabControl.PaintChildren().ActiveTabContentPaint(void*)(0x000000016b247790)
Fmx.Tabcontrol.TTabControl.PaintChildren()(??)
Fmx.Controls.TControl.PaintInternal().DoPaintInternal(void*)(0x000000016b247af8)
Fmx.Controls.TControl.PaintInternal().PaintAndClipChild(void*)(0x000000016b247af8)
Fmx.Controls.TControl.PaintInternal()(??)
Fmx.Forms.TCustomForm.PaintRects(System.Types.TRectF const*, int)(0x000000010c05ae00,0x000000016b247e30,0)
Fmx.Platform.Ios.TFMXMTKView3D.drawRect(Iosapi.Foundation.NSRect)(0x0000000281e7e7e0)
:00000001060F2DC0 DispatchToDelphi

![crash](https://user-images.githubusercontent.com/7482023/154804263-9ba6d28c-e209-49ae-85e3-6f423824e79e.png)

**Comment by viniciusfbb** [comment]
Problem confirmed! It is not related to GlobalEventDrivenDisplayUpdates, but GlobalUseMetal + effects/filters. While the issue only occurs with Skia Canvas enabled, it is not a Skia issue, but an FMX issue, specifically in the FMX.Context.Metal.TContextMetal.DoCopyToBits method, at line:

```delphi
    LTexture.getBytesBytesPerRowFromRegionMipmapLevel(
      Bits, // pixelBytes: Pointer;
      LBytesPerRow, // bytesPerRow: NSUInteger;
      LRegion, // fromRegion: MTLRegion;
      0); // mipmapLevel: NSUInteger
```
that should be:
```delphi
    LTexture.getBytesBytesPerRowFromRegionMipmapLevel(
      Bits, // pixelBytes: Pointer;
      Pitch, // <<<<<<<<<<<<<<<<<<<<<<<<<<<
      LRegion, // fromRegion: MTLRegion;
      0); // mipmapLevel: NSUInteger
```

I believe the DoCopyToBits function has never been tested before, because it is only called when there is a custom 2D canvas (which is our case). We had even discovered a problem in the same function of GLES (Android and iOS), FMX.Context.GLES.TCustomContextOpenGL.DoCopyToBits, we even reported it: https://quality.embarcadero.com/browse/RSP-36957

We will report this Metal issue to QualityCenter. The current workaround is to manually fix the FMX.Context.Metal.pas unit and add it to the project. To make the library easier to use and while the Embarcadero doesn't fix this, we'll try to patch this method at runtime with the fix already in the next release, just like we did with the AV in the FMX.Context.GLES unit: https://github.com/skia4delphi/skia4delphi/blob/81440e8d5f6c4e1e45d91f9aa58ee61ab3c5171d/Source/FMX/Skia.FMX.Graphics.pas#L1118

**Comment by viniciusfbb** [comment]
@FMXExpress Issue reported to Embarcadero: https://quality.embarcadero.com/browse/RSP-37147

We added a workaround to our code while Embarcadero fixes the issue. So, problem solved in new release, 3.1.0.

**Comment by viniciusfbb** [comment]
Note: I also noticed that the effects with Metal enabled, do not work correctly (at least the shadow). Some controls render the effect correctly while others do not. This is a problem in FMX's TContextMetal and is not related to Skia4Delphi (the same problem occur without Skia4Delphi). Our canvas implementation only changes the FMX's 2D canvas, while the 3D canvas (which is responsible for rendering 3D forms and 2D form effects/filters) remains the same as for FMX.

**Comment by viniciusfbb** [comment]
The "GlobalEventDrivenDisplayUpdates := False" is supported now in our new release [3.2.0](https://github.com/skia4delphi/skia4delphi/releases).
