### ISSUE TITLE
Installation failed (Delphi 11)

### ISSUE THREAD

**Issue by mitzix** [skia4delphi/skia4delphi#60]
Microsoft (R) Build Engine version 4.8.4084.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 21.02.2022 14:20:47.
Project "C:\DevTools\Comps\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj" on node 1 (default targets).
C:\Users\Michal\AppData\Roaming\Embarcadero\BDS\22.0\environment.proj(5,9): error MSB5016: The name "asl.log" contains an invalid character ".". [C:\DevTools\Comps\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj]
Done Building Project "C:\DevTools\Comps\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj" (default targets) -- FAILED.

Build FAILED.

"C:\DevTools\Comps\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj" (default target) (1) ->
  C:\Users\Michal\AppData\Roaming\Embarcadero\BDS\22.0\environment.proj(5,9): error MSB5016: The name "asl.log" contains an invalid character ".". [C:\DevTools\Comps\Skia4Delphi\Packages\RAD Studio 11.0 Alexandria\Skia.Package.RTL.dproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.02

**Comment by viniciusfbb** [comment]
Can you add @paulocesarbot on telegram? https://t.me/paulocesarbot

**Comment by mitzix** [comment]
Latest one. 3.0.0. This log is produced by installer.

**Comment by mitzix** [comment]
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <ALLUSERSPROFILE Condition="'$(ALLUSERSPROFILE)'==''">C:\ProgramData</ALLUSERSPROFILE>
        <APPDATA Condition="'$(APPDATA)'==''">C:\Users\Michal\AppData\Roaming</APPDATA>
        <asl_log Condition="'$(asl_log)'==''">Destination=file</asl_log>
        <BDS Condition="'$(BDS)'==''">c:\devtools\rad22</BDS>
        <BDSAppDataBaseDir Condition="'$(BDSAppDataBaseDir)'==''">BDS</BDSAppDataBaseDir>
        <BDSBIN Condition="'$(BDSBIN)'==''">c:\devtools\rad22\bin</BDSBIN>
        <BDSCatalogRepository Condition="'$(BDSCatalogRepository)'==''">C:\Users\Michal\Documents\Embarcadero\Studio\22.0\CatalogRepository</BDSCatalogRepository>
        <BDSCatalogRepositoryAllUsers Condition="'$(BDSCatalogRepositoryAllUsers)'==''">C:\Users\Public\Documents\Embarcadero\Studio\22.0\CatalogRepository</BDSCatalogRepositoryAllUsers>
        <BDSCOMMONDIR Condition="'$(BDSCOMMONDIR)'==''">C:\Users\Public\Documents\Embarcadero\Studio\22.0</BDSCOMMONDIR>
        <BDSINCLUDE Condition="'$(BDSINCLUDE)'==''">c:\devtools\rad22\include</BDSINCLUDE>
        <BDSLIB Condition="'$(BDSLIB)'==''">c:\devtools\rad22\lib</BDSLIB>
        <BDSPLATFORMSDKSDIR Condition="'$(BDSPLATFORMSDKSDIR)'==''">C:\Users\Michal\Documents\Embarcadero\Studio\SDKs</BDSPLATFORMSDKSDIR>
        <BDSPROFILESDIR Condition="'$(BDSPROFILESDIR)'==''">C:\Users\Michal\Documents\Embarcadero\Studio\Profiles</BDSPROFILESDIR>
        <BDSPROJECTSDIR Condition="'$(BDSPROJECTSDIR)'==''">C:\Users\Michal\Documents\Embarcadero\Studio\Projects</BDSPROJECTSDIR>
        <BDSUSERDIR Condition="'$(BDSUSERDIR)'==''">C:\Users\Michal\Documents\Embarcadero\Studio\22.0</BDSUSERDIR>
        <CommonProgramFiles Condition="'$(CommonProgramFiles)'==''">C:\Program Files (x86)\Common Files</CommonProgramFiles>
        <CommonProgramFiles_x86_ Condition="'$(CommonProgramFiles_x86_)'==''">C:\Program Files (x86)\Common Files</CommonProgramFiles_x86_>
        <CommonProgramW6432 Condition="'$(CommonProgramW6432)'==''">C:\Program Files\Common Files</CommonProgramW6432>
        <COMPUTERNAME Condition="'$(COMPUTERNAME)'==''">ELITE</COMPUTERNAME>
        <ComSpec Condition="'$(ComSpec)'==''">C:\windows\system32\cmd.exe</ComSpec>
        <DELPHI Condition="'$(DELPHI)'==''">c:\devtools\rad22</DELPHI>
        <DEMOSDIR Condition="'$(DEMOSDIR)'==''">C:\Users\Public\Documents\Embarcadero\Studio\22.0\Samples</DEMOSDIR>
        <DriverData Condition="'$(DriverData)'==''">C:\Windows\System32\Drivers\DriverData</DriverData>
        <ESET_OPTIONS Condition="'$(ESET_OPTIONS)'==''">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </ESET_OPTIONS>
        <HOMEDRIVE Condition="'$(HOMEDRIVE)'==''">C:</HOMEDRIVE>
        <HOMEPATH Condition="'$(HOMEPATH)'==''">\Users\Michal</HOMEPATH>
        <IBREDISTDIR Condition="'$(IBREDISTDIR)'==''">C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2020</IBREDISTDIR>
        <LOCALAPPDATA Condition="'$(LOCALAPPDATA)'==''">C:\Users\Michal\AppData\Local</LOCALAPPDATA>
        <LOGONSERVER Condition="'$(LOGONSERVER)'==''">\\ELITE</LOGONSERVER>
        <NUMBER_OF_PROCESSORS Condition="'$(NUMBER_OF_PROCESSORS)'==''">16</NUMBER_OF_PROCESSORS>
        <OneDrive Condition="'$(OneDrive)'==''">C:\Users\Michal\OneDrive - Jablonet s.r.o</OneDrive>
        <OneDriveCommercial Condition="'$(OneDriveCommercial)'==''">C:\Users\Michal\OneDrive - Jablonet s.r.o</OneDriveCommercial>
        <OneDriveConsumer Condition="'$(OneDriveConsumer)'==''">C:\Users\Michal\OneDrive</OneDriveConsumer>
        <OnlineServices Condition="'$(OnlineServices)'==''">Online Services</OnlineServices>
        <OS Condition="'$(OS)'==''">Windows_NT</OS>
        <Path Condition="'$(Path)'==''">C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2020\IDE_spoof;C:\DevTools\CS5\Deploy\Win32;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\DevTools\RAD22\bin;C:\Users\Public\Documents\Embarcadero\Studio\22.0\Bpl;C:\DevTools\RAD22\bin64;C:\DevTools\OpenSSL;C:\Users\Public\Documents\Embarcadero\Studio\21.0\Bpl;C:\Users\Public\Documents\Embarcadero\Studio\21.0\Bpl\Win64;C:\Program Files (x86)\Raize\CS5\Deploy\Win32;C:\Windows\Microsoft.NET\Framework\v1.1.4322\;C:\DevTools\BDS4\Bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\DevTools\RAD21\bin;C:\DevTools\RAD21\bpl;C:\DevTools\RAD21\dcp;C:\DevTools\RAD21\bin64;C:\DevTools\RAD5\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;d:\tools\BATCH;C:\Program Files\dotnet\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\AOMEI\AOMEI Backupper\6.8.0;C:\Program Files (x86)\dotnet\;c:\devtools\rad22\Bpl;c:\devtools\rad20\Bpl;c:\devtools\rad7\Bpl;c:\devtools\bds4\Bpl;c:\devtools\rad5\Bpl;c:\devtools\rad21\Bpl;C:\Users\Michal\AppData\Local\Microsoft\WindowsApps;C:\Users\Michal\.dotnet\tools</Path>
        <PATHEXT Condition="'$(PATHEXT)'==''">.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC</PATHEXT>
        <platformcode Condition="'$(platformcode)'==''">AN</platformcode>
        <PROCESSOR_ARCHITECTURE Condition="'$(PROCESSOR_ARCHITECTURE)'==''">x86</PROCESSOR_ARCHITECTURE>
        <PROCESSOR_ARCHITEW6432 Condition="'$(PROCESSOR_ARCHITEW6432)'==''">AMD64</PROCESSOR_ARCHITEW6432>
        <PROCESSOR_IDENTIFIER Condition="'$(PROCESSOR_IDENTIFIER)'==''">AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD</PROCESSOR_IDENTIFIER>
        <PROCESSOR_LEVEL Condition="'$(PROCESSOR_LEVEL)'==''">23</PROCESSOR_LEVEL>
        <PROCESSOR_REVISION Condition="'$(PROCESSOR_REVISION)'==''">6001</PROCESSOR_REVISION>
        <ProductVersion Condition="'$(ProductVersion)'==''">22.0</ProductVersion>
        <ProgramData Condition="'$(ProgramData)'==''">C:\ProgramData</ProgramData>
        <ProgramFiles Condition="'$(ProgramFiles)'==''">C:\Program Files (x86)</ProgramFiles>
        <ProgramFiles_x86_ Condition="'$(ProgramFiles_x86_)'==''">C:\Program Files (x86)</ProgramFiles_x86_>
        <ProgramW6432 Condition="'$(ProgramW6432)'==''">C:\Program Files</ProgramW6432>
        <PSModulePath Condition="'$(PSModulePath)'==''">C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules\</PSModulePath>
        <PUBLIC Condition="'$(PUBLIC)'==''">C:\Users\Public</PUBLIC>
        <RegionCode Condition="'$(RegionCode)'==''">EMEA</RegionCode>
        <RVMediaVCL Condition="'$(RVMediaVCL)'==''">C:\DevTools\Comps\RVMedia\Source</RVMediaVCL>
        <SystemDrive Condition="'$(SystemDrive)'==''">C:</SystemDrive>
        <SystemRoot Condition="'$(SystemRoot)'==''">C:\windows</SystemRoot>
        <TEMP Condition="'$(TEMP)'==''">d:\temp</TEMP>
        <TMP Condition="'$(TMP)'==''">d:\temp</TMP>
        <TRichViewVCLD Condition="'$(TRichViewVCLD)'==''">C:\DevTools\Comps\TRichView</TRichViewVCLD>
        <USERDOMAIN Condition="'$(USERDOMAIN)'==''">ELITE</USERDOMAIN>
        <USERDOMAIN_ROAMINGPROFILE Condition="'$(USERDOMAIN_ROAMINGPROFILE)'==''">ELITE</USERDOMAIN_ROAMINGPROFILE>
        <USERNAME Condition="'$(USERNAME)'==''">Michal</USERNAME>
        <USERPROFILE Condition="'$(USERPROFILE)'==''">C:\Users\Michal</USERPROFILE>
        <windir Condition="'$(windir)'==''">C:\windows</windir>
        <__COMPAT_LAYER Condition="'$(__COMPAT_LAYER)'==''">RunAsAdmin</__COMPAT_LAYER>
    </PropertyGroup>
    <ProjectExtensions>
        <Borland.Personality/>
        <Borland.ProjectType/>
        <BorlandProject/>
        <ProjectFileVersion>12</ProjectFileVersion>
    </ProjectExtensions>
</Project>

**Comment by viniciusfbb** [comment]
@mitzix The latest version is [3.0.3](https://github.com/skia4delphi/skia4delphi/releases/tag/v3.0.3) which fixes this problem in Sydney and Alexandria. Anyway, let's investigate the problem. In any case, we will investigate this problem further, as it still occurs in versions prior to Sydney, even in our latest release.

**Comment by mitzix** [comment]
I'm not able to attach or put xml content of environment.proj file here. It is converted from xml to text :(
I don't have Telegram.

**Comment by mitzix** [comment]
ok. Confirmed. Version 3.0.3 works fine. Thanks

**Comment by viniciusfbb** [comment]
Fixed issue for all versions of RAD Studio in new version [3.1.0](https://github.com/skia4delphi/skia4delphi/releases)
