### ISSUE TITLE
REQUEST: WrapMode Property in tSKSVG

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [skia4delphi/skia4delphi#62]
IMHO I think it's a bit of an oversight to have a WrapMode in the FSVG Brush but not as a published property of the tsKVG itself.

Just my two cents and it's trivial to implement

**Comment by viniciusfbb** [comment]
The idea was to base on TBrushBitmap/TBrush. It's great to put all the svg rendering in SkSvgBrush, it's easier for custom components to draw svg, or even third-party libraries (like ethea svgicons) without depending on a control.
