### ISSUE TITLE
Not Delayed DLL Load

### ISSUE THREAD

**Issue by hafedh-trimeche** [skia4delphi/skia4delphi#66]
Hello,

Please note that the library wont be dynamically loaded and the path path to it can't be set at runtime!

`exception class ESkiaAPI with message 'Skia library could not be loaded'.
`
The loading process would be changed to Delayed.

Best regards.

**Comment by viniciusfbb** [comment]
Hi @hafedh-trimeche, thank you very much to report the issue!

> the library wont be dynamically loaded

What exactly do you mean?

>  the path to it can't be set at runtime!

True, there is currently no such option. The workaround for this is to change the Skia.Api.pas. A small inconvenience of this is that with each compilation our plugin will continue copying the dll to the folder where your .exe is generated.

In the future we plan to add a static linking version, that is, a version that doesn't need dll. However, because it is something more laborious, we do not plan in the short term.

> The loading process would be changed to Delayed.

Delayed is a little slower.

**Comment by hafedh-trimeche** [comment]
Hi,

Thank you for your prompt response.

The best folder to place the DLL would be %APPDATA%.

Please also note that the Design Package can't be installed (the DLL should be loaded near the BDS Application).

Best regards.

**Comment by viniciusfbb** [comment]
> note that the Design Package can't be installed (the DLL should be loaded near the BDS Application).

Do you installed manually? If so, you skipped step 5 of [our manual installation documentation](https://github.com/skia4delphi/skia4delphi/blob/main/Documents/INSTALLATION.md):

#  

5. Open RAD Studio, go to *Tools > Options... > IDE > Environment Variables*, and:
   
   5.1. Click *New...*, and add the variable name `SKIADIR`, and in *variable value* put your **Skia4Delphi** full path *(eg C:\skia4delphi)*, and click *OK*. From here, we'll call this path as `[skia4delphi_root]` in this documentation. But remember: in the step that is written `[skia4delphi_root]`, it must be filled with full path (without environment variables);
   
   5.2. Still in the *Environment Variables* page, in the *User System Overrides* section, find the `PATH` variable and double click to change it. You need to add the these three folders (full path) at the beginning:
   
   - `[skia4delphi_root]\Binary\Win32\Release;`
     *eg C:\skia4delphi\Binary\Win32\Release;*
   - `[skia4delphi_root]\Library\[rad_version_name]\Win32\Release\Bpl;`
     *eg C:\skia4delphi\Library\RAD Studio 11.0 Alexandria\Win32\Release\Bpl;*
   - `[skia4delphi_root]\Library\[rad_version_name]\Win64\Release\Bpl;`
     *eg C:\skia4delphi\Library\RAD Studio 11.0 Alexandria\Win64\Release\Bpl;*
   
   5.3. Click *OK* and *Save*;

**Comment by viniciusfbb** [comment]
> The best folder to place the DLL would be %APPDATA%.

I don't know if this is true. A large number of applications are portable and all dependencies must be bundled with the .exe.

**Comment by viniciusfbb** [comment]
@hafedh-trimeche At the moment we are prioritizing bug fixes but in the future we can check for a better way to load on Windows. I'll close the issue for now, but feel free to create a new one in the future on the subject or if you have new suggestions. If you want too, you can send us pull requests with the improvements you want.

**Comment by kazuser** [comment]
> In the future we plan to add a static linking version, that is, a version that doesn't need dll.

So... has anything changed 2 years later? 🥲

**Comment by viniciusfbb** [comment]
@kazuser @hafedh-trimeche Fixed on new release **[v6.4.0-beta1](https://github.com/skia4delphi/skia4delphi/releases)**.
there is no longer any need to use sk4d.dll
