### ISSUE TITLE
TsKLabel BackgroundColor problem

### ISSUE THREAD

**Issue by Brnoch** [skia4delphi/skia4delphi#68]
Hi,
Thanks for the beautiful tool you give to us!
I'm very happy that you added the possibilty to define a background for the words added to the TsKLabel
There is only a small problem : when one line mixes text with different font sizes, the background can be shifted out (I'm not sure that it is the appropriated verb)
You can see the problem in the attachment.
![skia bug](https://user-images.githubusercontent.com/8734788/156162872-f7eeac39-896a-43bd-b2dd-65b8c7dad47a.png)

**Comment by Brnoch** [comment]
I add another very small issue : when there's a emoji inside a word, the background is not completely continuous : there are small gaps before and after the emoji
![skia pb 2](https://user-images.githubusercontent.com/8734788/156163212-93f86dfb-1654-4373-9649-a6613666a4a3.png)

**Comment by Brnoch** [comment]
(the word is space + emoji + space + text)

**Comment by viniciusfbb** [comment]
Hi @Brnoch, thank you very much for reporting the issue! We are planning a new version with this and other fixes in two days.

**Comment by Brnoch** [comment]
Thanks a lot @viniciusfbb. You're pretty quick :-)

**Comment by viniciusfbb** [comment]
@Brnoch Can you send me an example with the first problem? I can't reproduce it...

https://user-images.githubusercontent.com/11139086/156174018-d07ee1d8-f827-4cf1-bd2f-e6a40eec64d5.mp4

**Comment by viniciusfbb** [comment]
I was able to confirm the problem, it only occurs in TSkLabel of Vcl.

**Comment by Brnoch** [comment]
Fine. I use the Vcl indeed.

**Comment by Brnoch** [comment]
Hi
I just tested the new version 3.2.0. 
The background is still not completely centered vertically (I'm still using the VCL version).
![skia pb 3](https://user-images.githubusercontent.com/8734788/157293619-8741b00f-81fe-4e17-8bd6-3dca50cc4d7e.png)

**Comment by viniciusfbb** [comment]
Hi @Brnoch, seems to be expected.

See Microsoft Word:
![image](https://user-images.githubusercontent.com/11139086/157295239-4ff2aba7-eb3c-4509-b072-2cb03f4f7379.png)

See also websites of news:
<img src="https://user-images.githubusercontent.com/11139086/157295869-ff7d5677-870b-4221-89dd-08df0f9a4534.PNG" width="400" alt="news" />

**Comment by Brnoch** [comment]
You're right, it seems to be the norm. I'll follow it :-)
Thanks for your answer.
Btw, I hope the political situation in Brazil will improve in the next future!
