### ISSUE TITLE
Error at restart after uninstall of older Skia4Delphi, restart IDE, install latest Skia4Delphi

### ISSUE THREAD

**Issue by birbilis** [skia4delphi/skia4delphi#69]
![image](https://user-images.githubusercontent.com/3461504/156476885-5d996c31-767d-44fc-b7e1-cd30fe9a7983.png)

Had to uninstall the latest version again and restart the IDE, then install a 2nd time and restart and no error this time shown (hope it doesn't remember the previous selection to not load this package again - guess I'm ok now since I see the "Enable SKIA" option)

**Comment by birbilis** [comment]
btw, it showed two such messages I think (maybe for different packages), this is probably the 2nd message, don't remember

**Comment by viniciusfbb** [comment]
Hi @birbilis,

The packages with suffixes ".Delphi11Alexandria", like the one in the screenshot, are packages from the old version of Skia4Delphi (v2.xx). This leads me to believe that the uninstall was not done correctly. Probably you uninstalled manually and forgot to uninstall some packages. Despite this, it is likely that the installation of the new version was successful, so don't worry about this message, just click "No" when this message appears.

Anyway, I will improve the installer in the next release, to remove these old packages automatically during installation.

**Comment by birbilis** [comment]
did uninstall via GetIt, but don't remember which exact Skia4Delphi version I had before. Now it seems OK after uninstall again and reinstall of its latest version (aka done two times)

**Comment by viniciusfbb** [comment]
Improved setup in our new version [3.2.0](https://github.com/skia4delphi/skia4delphi/releases)
