### ISSUE TITLE
Fazer desenhos livres com diversas cores (question)

### ISSUE THREAD

**Issue by BoscoBecker** [skia4delphi/skia4delphi#70]
Olá tudo bem ?

Como é possível fazer desenhos livres com diversas cores selecionadadas.

Atualmente eu faco assim no envento OnDraw:

```Delphi
    LPaint.Color := ColorToAlphaColor(FSelectedColor);
    LPaint.SetPathEffect(TSkPathEffect.MakeCorner(50));
    LPaint.StrokeCap:=  TSkStrokeCap(FStroke);
    LPaint.StrokeWidth := FEspessura;

    for LPath in FOldPaths do
      ACanvas.DrawPath(LPath, LPaint);

    if Assigned(FPathBuilder) and not Assigned(FCurrentPath) then
      FCurrentPath := FPathBuilder.Snapshot;
    if Assigned(FCurrentPath) then
      ACanvas.DrawPath(FCurrentPath, LPaint);
```

Mas quando eu altero a cor ele altera todos os riscos feitos anteriormente pela nova cor selecionada,

Obrigado novamente.

**Comment by viniciusfbb** [comment]
Olá @BoscoBecker!

Você deve usar a lógica de programação para salvar cada path com a cor atual dele para que em cada redraw, cada path possa ser pintado com a cor desejada.

O desenho livre consiste em vários paths separados, que são salvos no vetor FOldPaths e na variável FCurrentPath. Cada vez que um path do desenho é alterado, a tela é limpada e todos os paths são redesenhados. Acontece que quando isso ocorre, todos os paths são redesenhados com a cor atual, pois os paths armazenam apenas as formas do desenho e não a cor do desenho. O correto é armazenar as cores da mesma forma como é armazenado os paths. Criar um vetor de cores FOldColors e a variável FCurrentColor, adaptando o código para isso.

O parte do código que você mostrou, poderia ser adaptada da seguinte forma:

```delphi
    LPaint.SetPathEffect(TSkPathEffect.MakeCorner(50));
    LPaint.StrokeCap := TSkStrokeCap(FStroke);
    LPaint.StrokeWidth := FEspessura;

    for var I: Integer := 0 to Length(FOldPaths) - 1 do
    begin
      LPaint.Color := ColorToAlphaColor(FOldColors[I]);
      ACanvas.DrawPath(FOldColors[I], LPaint);
    end;

    if Assigned(FPathBuilder) and not Assigned(FCurrentPath) then
      FCurrentPath := FPathBuilder.Snapshot;
    if Assigned(FCurrentPath) then
    begin
      LPaint.Color := ColorToAlphaColor(FCurrentColor);
      ACanvas.DrawPath(FCurrentPath, LPaint);
    end;
```

**Comment by BoscoBecker** [comment]
Muito Obrigado!!!
