### ISSUE TITLE
Performance drop in Fullscreen Mode

### ISSUE THREAD

**Issue by Iamjoosy** [skia4delphi/skia4delphi#74]
First, congratulations to this great project. All in all I see siginificant performance gains across all platforms. Given this and the fact that one Skia canvas would work across all supported Delphi platforms I hope that in the near future this will become the standard canvas for Delphi (at least in FMX).
More about my observation about a performance drop in Fullscreen Mode:
I have a very simple drawing application that implements a harmonic osscilator, simply moving a filled circle in a sinusoidal fashion across the screen. For this I use a TSKPaintBox. The redraw is driven in an TApplication.OnIdle event which results on my system to the following performance (Windows only):
GlobalUseSkia := False  approx. 300FPS
GlobalUseSkia:= True approx. 3000 FPS  (i.e. an order of magnitude faster !)
However, setting Fullscreen = True of the Form (or setting the BorderStyle to bsNone) both results in a drop of performance to about 1000FPS whereas  in the GlobalUseSkia = False case the frame rate only drops marginally to a little below 300 FPS.
So I am wondering what causes this perfromacne drop.

Test conditions;
Skia4Delphi 3.2.0
Windows 10 
Delphi 11

**Comment by Iamjoosy** [comment]
Hi, thanks for the quick reply. 
I tested with ``GlobalUseSkiaRasterWhenAvailable := True;`` and the performance dropped to approx 400 FPS in both conditions.
I will try to package the project up and upload it asap.

**Comment by Iamjoosy** [comment]
Okay, here is the test project - I hope Ihaven't forgotten anything
[Harmonic.zip](https://github.com/skia4delphi/skia4delphi/files/8199365/Harmonic.zip)
.

**Comment by Iamjoosy** [comment]
> Anyway, this is a good benchmark, in the future we can add something similar to our repository. :)

Feel free to use the code. You may want to replace the timing (TNyanClock) code with a simple standard Delphi TStopwatch.

**Comment by viniciusfbb** [comment]
Hi @Iamjoosy, we made many improvements to implementation under Windows, including performance improvements, in the new version [v3.3.0](https://github.com/skia4delphi/skia4delphi/releases)

**Comment by Iamjoosy** [comment]
Great, I will give v3.3.0 a try immediately . Thanks for your great work!
