### ISSUE TITLE
TSkPaintBox redraw / repaint

### ISSUE THREAD

**Issue by Iamjoosy** [skia4delphi/skia4delphi#76]
Maybe I have misunderstood the documantation that states : "Note: The TSkPaintBox has a drawing caching system. To force a drawing refresh, call TSkPaintBox.Redraw." 
But in the implementation of `TSkCustomControl.Paint;` in Line 1371 there is
`if (FDrawCacheKind <> TSkDrawCacheKind.Always) and (Canvas is TSkCanvasCustom) then` which means because TSKPaintBox has a DrawCacheKind = Raster that the TSkPaintBox gets redrawn on every (re)paint and in fact as far as I can see never gets chached.
But maybe I overlooked something (quite possible). Maybe you can shed some light on this.
I just try to better understand the inner workings of this, again, outstanding library that rightfully deserved the Spirit of Delphi Award.

**Comment by viniciusfbb** [comment]
Hi @Iamjoosy

I explained it better in this other issue: https://github.com/skia4delphi/skia4delphi/issues/65#issuecomment-1051358273

**Comment by Iamjoosy** [comment]
Thanks, this explaines it very well, and I now understand your rationale.  But I think you should change the documentation to something like this:
"Note: In case the Skia Canvas is not the default drawing canvas - i.e. `GlobalUseSkia = True` is not defined in the project file - The TSkPaintBox has a drawing caching system. To force a drawing refresh in that case, call TSkPaintBox.Redraw."

**Comment by viniciusfbb** [comment]
I agree!

**Comment by Iamjoosy** [comment]
On a different note, what would be your prefered channel to discuss more general considerations that would not qualitfy as "Issues" in a strict sense ?

**Comment by viniciusfbb** [comment]
You can use Github Issues for anything related to the library.

In addition, you can contact us directly via telegram:
[@viniciusfbb](https://t.me/viniciusfbb)
[@paulocesarbot](https://t.me/paulocesarbot)

**Comment by viniciusfbb** [comment]
> But I think you should change the documentation

Done! https://github.com/skia4delphi/skia4delphi#tskpaintbox
