### ISSUE TITLE
Incorrect cursor positioning in TMemo on Android 

### ISSUE THREAD

**Issue by Iamjoosy** [skia4delphi/skia4delphi#77]
Hi,
on Android using SKIA4Delphi in a TMemo the cursor is not moved at the end of line when Space is entered. This happens only on Android. 
SK4D 3.2.0
D11

**Comment by viniciusfbb** [comment]
Hi @Iamjoosy, thank you very much for reporting the issue.

Are you trying to use Right-To-Left?
Is your TMemo's HorzAlign set to "Leading"?

I tested it here and it is working as expected.

**Comment by viniciusfbb** [comment]
Confirmed issue.

**Comment by viniciusfbb** [comment]
Hi @Iamjoosy, this issue was fixed in new version [v3.3.0](https://github.com/skia4delphi/skia4delphi/releases)
