### ISSUE TITLE
Missing Spaces From TTMSFMXHTMLText Control Text Display

### ISSUE THREAD

**Issue by FMXExpress** [skia4delphi/skia4delphi#78]
On normal canvas and Metal canvas the spaces are there correctly. With the Skia canvas it doesn't draw the spaces. This is the  TTMSFMXHTMLText control from TMS FMX UI Pack. The HTML aspect of it is enabled. It draws the HTML okay just not the spaces.

This is on iOS.

![tmsproblem](https://user-images.githubusercontent.com/7482023/157881747-9cb8aead-e7fe-4666-ad1a-a459281bcf60.jpg)

**Comment by FMXExpress** [comment]
This did fix the issue.

**Comment by viniciusfbb** [comment]
Hi @FMXExpress, this issue was fixed in new version [v3.3.0](https://github.com/skia4delphi/skia4delphi/releases)
