### ISSUE TITLE
MouseMove problem when inserting LineBreak and links

### ISSUE THREAD

**Issue by Brnoch** [skia4delphi/skia4delphi#79]
Hi,
I encountered an issue when I inserted several lines integrating links and differents fontweights.
You can test it with the included code : as soon as the mouse moves over the label, an access violation rises.
Best regards,
Bruno
[test TskLabel.zip](https://github.com/skia4delphi/skia4delphi/files/8246277/test.TskLabel.zip)

**Comment by viniciusfbb** [comment]
Hi @Brnoch, thank you so much for reporting the issue!

We will fix on the next version that will be released later this week. The temporary workaround is to replace sLineBreak with #10.

**Comment by Brnoch** [comment]
Hi @viniciusfbb 
Thanks a lot for the quick fix, it works like a charm now

**Comment by viniciusfbb** [comment]
Hi @Brnoch, this issue was fixed in new version [v3.3.0](https://github.com/skia4delphi/skia4delphi/releases)
