### ISSUE TITLE
Mixing several fonts

### ISSUE THREAD

**Issue by Brnoch** [skia4delphi/skia4delphi#80]
Hi,
I don't know if it is a bug.
I wanted to use mix icons using the ttf version of the MS Fluent UI icons pack (https://github.com/microsoft/fluentui-system-icons/blob/master/fonts/FluentSystemIcons-Regular.ttf) and regular text, and they are not aligned properly horizontally.
![TsKLabel font hor align](https://user-images.githubusercontent.com/8734788/158246114-f2e3dc88-7c2e-4d15-908a-f5e2bbd3da9d.png)
Here is the corresponding code:
```delphi
  SKL_EventType.Words.Add(' ');
  SKL_EventType.Words.Add(WideChar($FD1E), SKL_EventType.TextSettings.FontColor, SKL_EventType.TextSettings.Font.Size).Font.Families := 'FluentSystemIcons-Regular';
  SKL_EventType.Words.Add(' (SegoeUIVariableText14) ');
  SKL_EventType.Words.Add(WideChar($F5BB), SKL_EventType.TextSettings.FontColor, SKL_EventType.TextSettings.Font.Size).Font.Families := 'FluentSystemIcons-Regular';
  SKL_EventType.Words.Add(' SegoeUIVariableText14 ');
  SKL_EventType.Words.Add(' Arial10 ', SKL_EventType.TextSettings.FontColor, SKL_EventType.TextSettings.Font.Size - 4).Font.Families := 'Arial';
```

**Comment by viniciusfbb** [comment]
Hi @Brnoch!

It seems to be a font problem. See the result of Microsoft Word vs TSkLabel:

![image](https://user-images.githubusercontent.com/11139086/158251066-6a096c9b-6354-4910-8e38-b35897a46b8b.png)

Also, Windows emojis render perfectly, so it seems like the font.

**Comment by Brnoch** [comment]
thanks @viniciusfbb, I should have tried in Word as you did!

**Comment by viniciusfbb** [comment]
I'll close it for now but if you have news you can post it here and I'll reopen.
