### ISSUE TITLE
Demo não esta funcionando - Delphi 10.4

### ISSUE THREAD

**Issue by fernandoleitebarreto** [skia4delphi/skia4delphi#86]
Estava usando a versao 3.0.3 e de repente começou a apresentar a mensagem:
COULD NOT INITIALIZE GRDIRECTCONTEXT

Atualizei a versão para 3.2.0 porém não está exibindo a mensagem e esta com uma tela branca na tela principal.
O mesmo acontece com o demo

![Skia4Delphi-Error(1)](https://user-images.githubusercontent.com/6810812/159600764-54eef352-8556-42f5-a707-b9ef988840d6.PNG)

**Comment by viniciusfbb** [comment]
Olá @fernandoleitebarreto, muito obrigado por reportar este problema!

Já estávamos cientes deste issue, que só ocorre em algumas máquinas Windows. Inclusive já temos o fix para isso, que estará disponível em nosso próximo release, provavelmente amanhã.

Até lá, um workaround seria adicionar na primeira linha do dpr o código:

`  GlobalUseSkiaRasterWhenAvailable := True;`

**Comment by viniciusfbb** [comment]
Olá @fernandoleitebarreto, este problema foi fixado na nova versão [v3.3.0](https://github.com/skia4delphi/skia4delphi/releases)
