### ISSUE TITLE
Preoblem rendreing  in TPopupMenu under Firemonkey 11.1

### ISSUE THREAD

**Issue by MazighusDZ** [skia4delphi/skia4delphi#87]
when GlobalUseSkia is enabled in the project the TPopupMenu and TPopup content are blacked

![image](https://user-images.githubusercontent.com/66381229/160000410-d0496113-114c-4fde-a8f3-35d9c46523a9.png)

**Comment by viniciusfbb** [comment]
Hi @MazighusDZ, thank you very much to report the issue.

This problem was reported in issue #71.

We will provide a fix in our next release (probably tomorrow). Until there, you can apply a workaround adding the to first line of your dpr the code:

`  GlobalUseSkiaRasterWhenAvailable := True;`

**Comment by MazighusDZ** [comment]
Ok thanks, i have add GlobalUseSkiaRasterWhenAvailable to my dpr and another issue appear in
Skia.FMX.Graphics.TSkCanvasRasterWindows.SwapBuffers ,  i compile it under Alexandria 11.1

[Project demo.zip](https://github.com/skia4delphi/skia4delphi/files/8346669/Project.demo.zip)


![image](https://user-images.githubusercontent.com/66381229/160036286-847e6991-e605-46b5-acee-e810e26f1626.png)

**Comment by viniciusfbb** [comment]
@MazighusDZ Thank you so much for reporting! We will fix this problem too.
