### ISSUE TITLE
WordClick not working ?

### ISSUE THREAD

**Issue by Brnoch** [skia4delphi/skia4delphi#90]
HI!
The onclick event of a word doesn't seem to work. Even in the demo application provided with the 3.3.0 version, nothing happens when I click on the linked text.

**Comment by viniciusfbb** [comment]
@Brnoch Can you redownload setup 3.3.0, reinstall and check if it's fixed?

**Comment by Brnoch** [comment]
@viniciusfbb  Yes, it's OK now . Just tested the demo application.
