### ISSUE TITLE
Best place to ask question about using skia4delphi

### ISSUE THREAD

**Issue by hsauro** [skia4delphi/skia4delphi#91]
What's the best place for asking questions (not bug reports) on using skai4delphi? 

Delphi-PRAXIS has third-party sub forums, could a forum be created there or is there somewhere that already exists to post questions?

**Comment by viniciusfbb** [comment]
Hi @hsauro, you can ask any question here at GitHub, or you can ask in our telegram group too: https://t.me/skia4delphi (most conversations are in portuguese but you can ask in english too)
