### ISSUE TITLE
Stuck after resizing window by using Skia canvas

### ISSUE THREAD

**Issue by PonyPC** [skia4delphi/skia4delphi#93]
[Z.zip](https://github.com/skia4delphi/skia4delphi/files/8418868/Z.zip)

**Comment by viniciusfbb** [comment]
Thank you very much to reporting the issue!

I don't know if I understand correctly, the problem is about the quality of the texts during rotation?

**Comment by PonyPC** [comment]
Try to resize the window, maximize or move the grip. Then the whole window is stuck.

**Comment by PonyPC** [comment]
If you double click to run Project1.exe, it will show a runtime error

**Comment by PonyPC** [comment]
Hi, I enabled Skia but sk4d.dll was not copied to Debug or Release directory after compile.
I closed the IDE and open it compile again, then the sk4d.dll was generated.
The runtime error is no more existing.

The problem does not occur in GlobalUseSkiaRasterWhenAvailable := True;
The program is tested in virtual machines.

**Comment by viniciusfbb** [comment]
@PonyPC could you contact us via telegram? https://t.me/ski4delphi

**Comment by viniciusfbb** [comment]
@PonyPC could you contact us via telegram? https://t.me/skia4delphi

**Comment by PonyPC** [comment]
Sorry I can't login the telegram

**Comment by PonyPC** [comment]
Sorry I can't login the telegram

**Comment by PonyPC** [comment]
Ok

**Comment by PonyPC** [comment]
paulocesarbot didn't make response for 2 hours.

**Comment by viniciusfbb** [comment]
@PonyPC, we fixed all the issues found on Windows when using OpenGL, but there are still some inconsistencies (only on Windows), which occur specific situations (mainly in some VMs).

Bearing in mind that Raster on Windows performs similarly to Canvas using OpenGL, we decided that by default it will use Raster (only on Windows), and whoever wants to can set GlobalUseRasterWhenAvailable to False to use OpenGL, which can be interesting if the developer uses shaders in his application.

I also explained a bit about it in the description of our new release: [v3.3.2](https://github.com/skia4delphi/skia4delphi/releases/tag/v3.3.2)
