### ISSUE TITLE
TSkAnimatedImage play and stop missed

### ISSUE THREAD

**Issue by acarlomagno** [skia4delphi/skia4delphi#95]
Hi,
first, compliments! for the library!
I have read that there are no methods to start or stop an animation manually, but you have to use TSkAnimatedImage.enable or TSkAnimatedImage.visible.
I think a play / stop method allows you to better manage an animation ... for example a bell of the notifications ... as soon as a new one arrives ... the bell moves.
Using enable / visible the bell is always hidden ... and would only be seen during animation.
Another example that could be an animation for a process progress ... when it is active it moves ... when it is deactivated the image is still.

thank you
Antonello

**Comment by jimmckeeth** [comment]
Agreed. Here is a useful workaround in the meantime:

```
type 
  TAnimatedImageHack = Class(TSkAnimatedImage)
    public property DisabledOpacity;
  end;

procedure TForm12.FormCreate(Sender: TObject);
begin
  TAnimatedImageHack(SkAnimatedImage1).DisabledOpacity := 1;
```

then you can just use `SkAnimatedImage1.Enabled := True` or `False` to play and pause.

**Comment by viniciusfbb** [comment]
In the new version [v3.4.0](https://github.com/skia4delphi/skia4delphi/releases) we fixed opacity when disabled, as Jim suggested. So to control start and stop just use Enabled true or false. In the next version I will add more properties to be able to better control the animations, like: Inverse, AutoReverse, Delay, StartFromCurrent. The idea will be to do something similar to FMX's TAnimation.

**Comment by jimmckeeth** [comment]
Very nice!

**Comment by acarlomagno** [comment]
great! perfect

**Comment by acarlomagno** [comment]
> In the new version [v3.4.0](https://github.com/skia4delphi/skia4delphi/releases) we fixed opacity when disabled, as Jim suggested. So to control start and stop just use Enabled true or false. In the next version I will add more properties to be able to better control the animations, like: Inverse, AutoReverse, Delay, StartFromCurrent. The idea will be to do something similar to FMX's TAnimation.

I would add how many times the animation has to repeat ... n loop
