### ISSUE TITLE
DBImage não mostra mais, depois de usar o Skia em qualquer form.

### ISSUE THREAD

**Issue by RafaelVulpe** [skia4delphi/skia4delphi#99]
Bom dia, estou tendo um problema, no meu projeto uso o DBimage com imagens em .bmp e em um outro form usei o svg do skia, depois disso todos os DBimage do projeto pararam de mostrar a imagem que está gravada no banco de dados no campo Blob.

Alguem poderia me ajudar ?

**Comment by viniciusfbb** [comment]
Olá Rafael, muito obrigado por reportar o problema!

Sua aplicação é Vcl ou FMX? Se for FMX, vc está usando GlobalUseSkia := True; no dpr?

**Comment by RafaelVulpe** [comment]
Estou usando vcl. Cliquei com o botão direito do mouse em project e habilitei o Skia (mais isso não fez da o problema), o problema está quando informo no uses o skia ou o skia.vcl, neste caso todo o restante do projeto passa a não exibir mais os bitmaps no DBImage as imagens carregadas no TImage funcionaram normalmente, acredito que devido eu estar usando png nesses casos de TImage.

**Comment by viniciusfbb** [comment]
Certo, vamos fixar este problema no próximo release. Até lá acredito que um workaround poderia ser adicionar ao OnCreate do main form, a linha:

```delphi
  TPicture.RegisterFileFormat('bmp', 'Bitmap', TBitmap);
```

Pode me confirmar se este workaround funciona?

**Comment by RafaelVulpe** [comment]
Funcionou colocando antes do Application.Initialize; em Project -> View Source. 

Muito Obrigado pela atenção Vinicius.

**Comment by viniciusfbb** [comment]
Fixed in new version [v3.4.0](https://github.com/skia4delphi/skia4delphi/releases)
